### ISSUE TITLE
Does not work strapi start since v3.6

### ISSUE THREAD

**Issue by pkolt** [strapi/strapi#10146]
### Describe the bug

After upgrading the project to version 3.6, it starts with an error.

### Steps to reproduce the behavior

1. Update all strap modules to version 3.6 ;
2. Run `strapi start` .

### Expected behavior

Run Command `strapi start` - Works.

### Screenshots

<img width="696" alt="2021-04-26 в 18 39 07" src="https://user-images.githubusercontent.com/478905/116105125-7450f780-a6ca-11eb-8666-17631ee4f78d.png">

<img width="1409" alt="2021-04-26 в 18 40 08" src="https://user-images.githubusercontent.com/478905/116105111-6f8c4380-a6ca-11eb-87aa-e8c9ba09c47c.png">

### Code snippets

package.json:

```json
{
  "name": "server",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "ENV_PATH=.env.development strapi develop",
    "start": "ENV_PATH=.env.production strapi start",
    "build": "ENV_PATH=.env.production strapi build --clean"
  }
}
```

run server:

```bash
npm start
```

### System

- Node.js version: 14.15.0
- NPM version: 6.14.8
- Strapi version: 3.6
- Database: MySQL
- Operating system: Debian GNU/Linux 10 (buster)

### Additional context

The same project runs successfully on version 3.5.4.
At the same time, the build (`strapi build`) command works on version 3.6.

**Comment by alexandrebodin** [comment]
can you try to run npm rebuild it looks like a binary issue (we updated a low level dependency for image processing: sharp) that might be coming from this.

**Comment by pkolt** [comment]
@alexandrebodin

I executed the command `npm rebuild`

And then I executed the command `npm start` (`strapi start`)

The error was displayed again:

```
> server@0.1.0 start /home/pkolt/projects/test.dino-shop96.ru/server
> ENV_PATH=.env.production strapi start

Illegal instruction
npm ERR! code ELIFECYCLE
npm ERR! errno 132
npm ERR! server@0.1.0 start: `ENV_PATH=.env.production strapi start`
npm ERR! Exit status 132
npm ERR! 
npm ERR! Failed at the server@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pkolt/.npm/_logs/2021-04-26T15_38_54_168Z-debug.log
```

**Comment by alexandrebodin** [comment]
Ok have you cleaned / deleted your package-lock.json file before upgrading ?

**Comment by pkolt** [comment]
@alexandrebodin 

I run:

1. `rm package-lock.json`
2. `rm -rf node_modules`
3. `npm i`
4. npm start (strapi start)

The error was repeated again:

```
pkolt@pkolt-server:~/projects/test.dino-shop96.ru/server$ npm start

> server@0.1.0 start /home/pkolt/projects/test.dino-shop96.ru/server
> ENV_PATH=.env.production strapi start

Illegal instruction
npm ERR! code ELIFECYCLE
npm ERR! errno 132
npm ERR! server@0.1.0 start: `ENV_PATH=.env.production strapi start`
npm ERR! Exit status 132
npm ERR! 
npm ERR! Failed at the server@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pkolt/.npm/_logs/2021-04-26T16_32_35_862Z-debug.log
```

**Comment by snadal** [comment]
The same happens to us.

Strapi docker 3.6 does not start, either. I've tried the following docker-compose files:

`version: '3'
services:
  strapi:
    image: strapi/strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    tty: true`

`version: '3'
services:
  strapi:
    image: strapi/strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'`

My guess is that it is related to CPU. We are using AMD Opteron 2373 EE on VMWare ESXi, with different Guest OS with no luck.

`processor       : 7
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : Quad-Core AMD Opteron(tm) Processor 2373 EE
stepping        : 2
cpu MHz         : 2100.000
cache size      : 512 KB
physical id     : 14
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 14
initial apicid  : 14
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl tsc_reliable nonstop_tsc pni cx16 popcnt hypervisor lahf_lm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw vmmcall
bugs            : tlb_mmatch fxsave_leak sysret_ss_attrs
bogomips        : 4200.00
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual
power management:
`
The same docker-compose runs fine on different server (i.e, OVH Sandbox cloud instance running CentOS 8).

**Comment by haldarmahesh** [comment]
@pkolt can you share your package.json?

**Comment by pkolt** [comment]
Hi @haldarmahesh !

package.json

```
{
  "name": "server",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "ENV_PATH=.env.development strapi develop",
    "start": "ENV_PATH=.env.production strapi start",
    "build": "ENV_PATH=.env.production strapi build --clean",
    "build:dev": "ENV_PATH=.env.development strapi build --clean",
    "strapi": "strapi",
    "format": "prettier --check api/ config/ extensions/",
    "format:fix": "prettier --write api/ config/ extensions/",
    "pre-push": "npm run format",
    "check-ts": "tsc",
    "check-updates": "ncu -i",
    "build-types": "swagger-typescript-api -p ./extensions/documentation/documentation/1.0.0/full_documentation.json -o ./types -n index.ts --no-client --silent && node scripts/patch-types.js"
  },
  "devDependencies": {
    "husky": "^6.0.0",
    "npm-check-updates": "^11.5.3",
    "prettier": "^2.2.1",
    "swagger-typescript-api": "^8.0.3",
    "typescript": "^4.2.4"
  },
  "dependencies": {
    "knex": "0.95.4",
    "mysql": "^2.18.1",
    "strapi": "^3.6.0",
    "strapi-admin": "^3.6.0",
    "strapi-connector-bookshelf": "^3.6.0",
    "strapi-plugin-content-manager": "^3.6.0",
    "strapi-plugin-content-type-builder": "^3.6.0",
    "strapi-plugin-documentation": "^3.6.0",
    "strapi-plugin-email": "^3.6.0",
    "strapi-plugin-upload": "^3.6.0",
    "strapi-plugin-users-permissions": "^3.6.0",
    "strapi-utils": "^3.6.0",
    "telegraf": "^4.3.0"
  },
  "strapi": {
    "uuid": "591b9ed9-9663-49d0-b280-122b090a85c2"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": "^6.0.0"
  }
}
```

**Comment by derrickmehaffy** [comment]
Based on this (which is not recommended)

```
    "strapi": "^3.6.0",
    "strapi-admin": "^3.6.0",
    "strapi-connector-bookshelf": "^3.6.0",
    "strapi-plugin-content-manager": "^3.6.0",
    "strapi-plugin-content-type-builder": "^3.6.0",
    "strapi-plugin-documentation": "^3.6.0",
    "strapi-plugin-email": "^3.6.0",
    "strapi-plugin-upload": "^3.6.0",
    "strapi-plugin-users-permissions": "^3.6.0",
    "strapi-utils": "^3.6.0",
```

Did you run an `npm audit --fix` as that would break a ton of stuff.

**Comment by pkolt** [comment]
Hi @derrickmehaffy !

> Based on this (which is not recommended)

Didn't understand what is not recommended? Version 3.6?

> Did you run an npm audit --fix as that would break a ton of stuff.

Here, too, did not understand you. I didn't run `npm audit --fix`. How does this relate to my error?

**Comment by derrickmehaffy** [comment]
> Didn't understand what is not recommended? Version 3.6?

The carots `^`, these shouldn't be used with Strapi-maintained packages and we don't set these by default so something has been done that would update these.

**Comment by pkolt** [comment]
Hi @derrickmehaffy !

Yes you are right. I am using utility `ncu -i` (npm-check-updates) to update packages.

Is there anything you can recommend? How to overcome this error? Thanks.

**Comment by derrickmehaffy** [comment]
Delete the following files and folders:

- .cache
- build
- node_modules
- package-lock.json
- yarn.lock

Then update your package.json like so:

```json
{
  "name": "server",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "ENV_PATH=.env.development strapi develop",
    "start": "ENV_PATH=.env.production strapi start",
    "build": "ENV_PATH=.env.production strapi build --clean",
    "build:dev": "ENV_PATH=.env.development strapi build --clean",
    "strapi": "strapi",
    "format": "prettier --check api/ config/ extensions/",
    "format:fix": "prettier --write api/ config/ extensions/",
    "pre-push": "npm run format",
    "check-ts": "tsc",
    "check-updates": "ncu -i",
    "build-types": "swagger-typescript-api -p ./extensions/documentation/documentation/1.0.0/full_documentation.json -o ./types -n index.ts --no-client --silent && node scripts/patch-types.js"
  },
  "devDependencies": {
    "husky": "^6.0.0",
    "prettier": "^2.2.1",
    "swagger-typescript-api": "^8.0.3",
    "typescript": "^4.2.4"
  },
  "dependencies": {
    "knex": "0.95.4",
    "mysql": "^2.18.1",
    "strapi": "3.6.1",
    "strapi-admin": "3.6.1",
    "strapi-connector-bookshelf": "3.6.1",
    "strapi-plugin-content-manager": "3.6.1",
    "strapi-plugin-content-type-builder": "3.6.1",
    "strapi-plugin-documentation": "3.6.1",
    "strapi-plugin-email": "3.6.1",
    "strapi-plugin-upload": "3.6.1",
    "strapi-plugin-users-permissions": "3.6.1",
    "strapi-utils": "3.6.1",
    "telegraf": "^4.3.0"
  },
  "strapi": {
    "uuid": "591b9ed9-9663-49d0-b280-122b090a85c2"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": "^6.0.0"
  }
}
```

**Do not use ncu with Strapi projects**

- Reinstall node_modules
- Rebuild Admin
- Try to start application

---

Side point, we don't natively support typescript yet

**Comment by coderdix** [comment]
I'm getting the following issues in my build (I had all the aforementioned directories deleted)

`npm WARN ERESOLVE overriding peer dependency
npm WARN Found: graphql@15.5.0
npm WARN node_modules/graphql
npm WARN   graphql@"15.5.0" from strapi-plugin-graphql@3.6.1
npm WARN   node_modules/strapi-plugin-graphql
npm WARN     strapi-plugin-graphql@"^3.6.1" from the root project
npm WARN   4 more (@apollo/federation, @graphql-tools/utils, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from graphql-iso-date@3.6.1
npm WARN node_modules/graphql-iso-date
npm WARN   graphql-iso-date@"^3.6.1" from strapi-plugin-graphql@3.6.1
npm WARN   node_modules/strapi-plugin-graphql
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: graphql@15.5.0
npm WARN node_modules/graphql
npm WARN   graphql@"15.5.0" from strapi-plugin-graphql@3.6.1
npm WARN   node_modules/strapi-plugin-graphql
npm WARN     strapi-plugin-graphql@"^3.6.1" from the root project
npm WARN   4 more (@apollo/federation, @graphql-tools/utils, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from graphql-type-long@0.1.1
npm WARN node_modules/graphql-type-long
npm WARN   graphql-type-long@"^0.1.1" from strapi-plugin-graphql@3.6.1
npm WARN   node_modules/strapi-plugin-graphql
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@casl/ability@4.1.6',
npm WARN EBADENGINE   required: { npm: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.21.0', npm: '7.11.1' }
npm WARN EBADENGINE }
[1]    27583 killed     npm installiming idealTree Completed in 35207ms`

**Comment by pkolt** [comment]
Hi @derrickmehaffy !

Unfortunately, your recommendations did not help me.

I also tried creating a completely blank project from scratch (https://github.com/pkolt/example_strapi).

I am running:

1. `npm run build`
2. `npm start`

And again I get the error **Illegal instruction**:

<img width="1440" alt="Снимок экрана 2021-05-01 в 10 57 59" src="https://user-images.githubusercontent.com/478905/116772995-2b9f9280-aa6c-11eb-9a6c-6ef5a4f1739b.png">

**Comment by snadal** [comment]
Please could you paste the results of

`cat /proc/cpuinfo`

on the computer you are having the issue?

**Comment by pkolt** [comment]
Hi @snadal !

Output command `cat /proc/cpuinfo`:

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 28
model name	: Intel(R) Atom(TM) CPU D525   @ 1.80GHz
stepping	: 10
microcode	: 0x107
cpu MHz		: 1795.506
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
bugs		:
bogomips	: 3591.01
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 28
model name	: Intel(R) Atom(TM) CPU D525   @ 1.80GHz
stepping	: 10
microcode	: 0x107
cpu MHz		: 1795.506
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl cpuid aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
bugs		:
bogomips	: 3591.01
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

The problem is only on the server. There is no error when running on a MacBook.
But the strapy worked on the server in version 3.5.4!

**Comment by snadal** [comment]
As I said on my previous message (I may be wrong!), my guess is that some native package needs an instruction set that it is not available in older CPUS as I am facing the same situation. It runs on newer computers but not on older servers.

I've filtered the flags on the processor that we are currently running it (Haswell, with success) against the flags in Atom-D525 and AMD Opteron 2373 EE. The following ones are missing:

```
aes
arat
avx
avx2
bmi1
bmi2
cpuid_fault
ept
ept_ad
erms
f16c
flexpriority
fma
fsgsbase
invpcid
invpcid_single
md_clear
movbe
pcid
pclmulqdq
pti
rdrand
smep
sse4_1
sse4_2
ssse3
tpr_shadow
tsc_deadline_timer
tsc_known_freq
vmx
vnmi
vpid
x2apic
xsave
xsaveopt
xtopology
```

I've no idea which one could be the missing that is needed. Maybe some developer could tell which updated packages uses binary / native code so that we can open an issue in the specific package ?

**Comment by derrickmehaffy** [comment]
> The problem is only on the server.

What server and where is it hosted?

**Comment by avirankatzsofi** [comment]
Strapi fails to start for me either after the upgrade. I'm using mongoDB

**Comment by snadal** [comment]
@avirankatzsofi could you please paste the results of running

`cat /proc/cpuinfo`

on the computer you are having the issue?

**Comment by avirankatzsofi** [comment]
Sure:
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
stepping	: 11
microcode	: 0xb8
cpu MHz		: 2000.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass mds swapgs itlb_multihit srbds
bogomips	: 3999.93
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
stepping	: 11
microcode	: 0xb8
cpu MHz		: 2000.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass mds swapgs itlb_multihit srbds
bogomips	: 3999.93
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
stepping	: 11
microcode	: 0xb8
cpu MHz		: 2000.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass mds swapgs itlb_multihit srbds
bogomips	: 3999.93
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
stepping	: 11
microcode	: 0xb8
cpu MHz		: 1403.728
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass mds swapgs itlb_multihit srbds
bogomips	: 3999.93
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 4
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
stepping	: 11
microcode	: 0xb8
cpu MHz		: 2000.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass mds swapgs itlb_multihit srbds
bogomips	: 3999.93
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 5
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
stepping	: 11
microcode	: 0xb8
cpu MHz		: 2000.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass mds swapgs itlb_multihit srbds
bogomips	: 3999.93
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 6
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
stepping	: 11
microcode	: 0xb8
cpu MHz		: 2000.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 5
initial apicid	: 5
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass mds swapgs itlb_multihit srbds
bogomips	: 3999.93
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
stepping	: 11
microcode	: 0xb8
cpu MHz		: 900.025
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass mds swapgs itlb_multihit srbds
bogomips	: 3999.93
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

**Comment by snadal** [comment]
Sorry @avirankatzsofi, it seems that your case is different to the one that is affecting @pkolt and me.

My guess was that our issue is related to `sharp` package and binary library `libvirt` used by `sharp`

Strapi 3.5.x uses sharp 0.27.2, while Strapi 3.6.x uses sharp 0.28.2 

So I tried to reproduce the issue testing `sharp` package.
- 0.28.0: Illegal instruction error.
- 0.27.2: Everything seems to work fine.

Then I enabled core dumps:
`$ ulimit -c unlimited`

So when running `$ npm test` on `sharp 0.28.0`  you get the core dump.

```
➜  sharp git:(7555378) npm test
> sharp@0.28.0 test /home/user/sharp
> semistandard && cpplint && npm run test-unit && npm run test-licensing
> sharp@0.28.0 test-unit /home/user/sharp
> nyc --reporter=lcov --branches=99 mocha --slow=1000 --timeout=60000 ./test/unit/*.js
Illegal instruction (core dumped)
npm ERR! code ELIFECYCLE

```

Next inspect the core file with gdb to find out which instruction is causing the Illegal Instruction

```
➜  sharp git:(7555378) ✗ gdb node core
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
El núcleo se generó por «node /home/user/sharp/node_modules/.bin/mocha --slow=1000 --timeout».
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00007f6c9cdbdf1f in ?? () from /home/user/sharp/build/Release/../../vendor/8.10.6/lib/libvips-cpp.so.42
[Current thread is 1 (Thread 0x7f6ca6094740 (LWP 4060))]
```

Cool. Position 0x00007f6c9cdbdf1f is where we should look at.

Change to asm layout 
`(gdb) layout asm`

And you will see the root cause:
`0x7f6c9cdbdf1f  pinsrq $0x1,%rax,%xmm0`

`pinsrq`  is part of SSE4 extension. Neither Opteron nor Atom(TM) CPU D525 include it.

So it seems that **Strapi 3.6 needs SSE4 enabled in the CPU**.

A **REALLY** quick and dirty fix is to manually overwrite libvips 8.10.6 with 8.10.5

`wget https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-linux-x64.tar.br -O  /home/[USERNAME]/.npm/_libvips/libvips-8.10.6-linux-x64.tar.br`

It won't last, however, as new versions it is expected to be released with the same gcc flags, but coud you please try this workaround to see if Strapi starts correctly on your server?

Best

**Comment by avirankatzsofi** [comment]
@snadal after upgrading to v3.6.2 strapi starts successfully. Did you revert the sharp version?

**Comment by snadal** [comment]
@avirankatzsofi As I said, your issue does not seems to be related to this ticket. Your case may have been fixed in this PR https://github.com/strapi/strapi/pull/10281

This ticket is regarding running Strapi in processors without SSE4 extensions.

@derrickmehaffy you tagged this case as “can’t reproduce”. Any chance to keep sharp version on 0.27.x in Strapi?

**Comment by pkolt** [comment]
> > The problem is only on the server.
> 
> What server and where is it hosted?

Hi @derrickmehaffy !
It is home server. I can give you access if needed.

**Comment by derrickmehaffy** [comment]
> @avirankatzsofi As I said, your issue does not seems to be related to this ticket. Your case may have been fixed in this PR #10281
> 
> This ticket is regarding running Strapi in processors without SSE4 extensions.
> 
> @derrickmehaffy you tagged this case as “can’t reproduce”. Any chance to keep sharp version on 0.27.x in Strapi?

No, as we updated to support the new M1 Apple Macs, I would suggest reporting the issue to the Sharp team so they can fix it. 
https://github.com/strapi/strapi/blob/43b947b2ba2f153dd6056e0710d7dcd92fb9bc7c/packages/strapi-plugin-upload/package.json#L38

https://github.com/strapi/strapi/pull/10013

**Comment by she11sh0cked** [comment]
> Sorry @avirankatzsofi, it seems that your case is different to the one that is affecting @pkolt and me.
> 
> My guess was that our issue is related to `sharp` package and binary library `libvirt` used by `sharp`
> 
> Strapi 3.5.x uses sharp 0.27.2, while Strapi 3.6.x uses sharp 0.28.2
> 
> So I tried to reproduce the issue testing `sharp` package.
> 
> * 0.28.0: Illegal instruction error.
> * 0.27.2: Everything seems to work fine.
> 
> Then I enabled core dumps:
> `$ ulimit -c unlimited`
> 
> So when running `$ npm test` on `sharp 0.28.0` you get the core dump.
> 
> ```
> ➜  sharp git:(7555378) npm test
> > sharp@0.28.0 test /home/user/sharp
> > semistandard && cpplint && npm run test-unit && npm run test-licensing
> > sharp@0.28.0 test-unit /home/user/sharp
> > nyc --reporter=lcov --branches=99 mocha --slow=1000 --timeout=60000 ./test/unit/*.js
> Illegal instruction (core dumped)
> npm ERR! code ELIFECYCLE
> ```
> 
> Next inspect the core file with gdb to find out which instruction is causing the Illegal Instruction
> 
> ```
> ➜  sharp git:(7555378) ✗ gdb node core
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> El núcleo se generó por «node /home/user/sharp/node_modules/.bin/mocha --slow=1000 --timeout».
> Program terminated with signal SIGILL, Illegal instruction.
> #0  0x00007f6c9cdbdf1f in ?? () from /home/user/sharp/build/Release/../../vendor/8.10.6/lib/libvips-cpp.so.42
> [Current thread is 1 (Thread 0x7f6ca6094740 (LWP 4060))]
> ```
> 
> Cool. Position 0x00007f6c9cdbdf1f is where we should look at.
> 
> Change to asm layout
> `(gdb) layout asm`
> 
> And you will see the root cause:
> `0x7f6c9cdbdf1f pinsrq $0x1,%rax,%xmm0`
> 
> `pinsrq` is part of SSE4 extension. Neither Opteron nor Atom(TM) CPU D525 include it.
> 
> So it seems that **Strapi 3.6 needs SSE4 enabled in the CPU**.
> 
> A **REALLY** quick and dirty fix is to manually overwrite libvips 8.10.6 with 8.10.5
> 
> `wget https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-linux-x64.tar.br -O /home/[USERNAME]/.npm/_libvips/libvips-8.10.6-linux-x64.tar.br`
> 
> It won't last, however, as new versions it is expected to be released with the same gcc flags, but coud you please try this workaround to see if Strapi starts correctly on your server?
> 
> Best

Hi @snadal !

I tested it with sharp v0.28.1. Same issue.
Curiously it still throws at `0x00007f315e5c0f1f`, even after replacing libvips!

I'm running an Atom N2800 CPU btw.

Has anyone already opened an issue at sharp's repo?

**Comment by derrickmehaffy** [comment]
I'm going to set this one as closed as I don't believe it's an issue with Strapi specifically unless someone wants to test with sharp v0.28.2 or v0.28.3 that's about all we can do (we won't downgrade dependencies as it will break usage with other users.)

If an issue hasn't been opened with sharp, someone who has the issue and can relay the information from this one there should.

**Comment by derrickmehaffy** [comment]
(Although this is closed, please feel free to continue the discussion if you wish)

**Comment by pkolt** [comment]
Hi! I created an issue in [sharp repo](https://github.com/lovell/sharp/issues/2809), because the problem is in sharp.
I was able to reproduce the bug on sharp@0.28.3 without using a strapi. Thanks.

**Comment by derrickmehaffy** [comment]
Thank you for opening that  and confirming the issue isn't directly with Strapi. :+1:

**Comment by leandro-machado-costa** [comment]
Hi, I have the same problem on strapi 4.2.0
![image](https://user-images.githubusercontent.com/3492440/175969994-0c273d3b-94f6-4109-b139-09cf030d52a4.png)

![image](https://user-images.githubusercontent.com/3492440/175970099-7cb4e401-2988-491e-b823-d1499c3429f3.png)

Could you help me to solve this?

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
