### ISSUE TITLE
[API Tokens] 403 response when requesting /api/content-type-builder/content-types endpoint

### ISSUE THREAD

**Issue by soupette** [strapi/strapi#12197]
### Steps to reproduce the behavior

Requesting the `/api/content-type-builder/content-types` endpoint with a valid api token returns a 403 response:

1. Create a Read Only token using the interface.
2. Try to request one of the endpoint of the content type builder content api
3. See the 403 response status.

### Expected behavior

The API token feature should work when requesting the content api of the content type builder plugin.

### Screenshots

N/A

### Code snippets

```js
require('dotenv').config({
  path: `.env`,
});

const axios = require('axios').default;

const createInstance = (config) => {
  const headers = { ...config?.headers };

  if (config.accessToken) {
    headers.authorization = `Bearer ${config.accessToken}`;
  }

  const instance = axios.create({
    baseURL: config.apiURL,
    headers,
  });

  instance.interceptors.response.use((response) => response.data);

  return instance;
};

const run = async () => {
  const strapiConfig = {
    apiURL: process.env.STRAPI_API_URL,
    accessToken: process.env.STRAPI_TOKEN,
  };

  const axiosInstance = createInstance(strapiConfig);

  try {
    const { data: contentTypesSchemas } = await axiosInstance.get(
      '/content-type-builder/content-types',
    );
  } catch (err) {
    console.log(err);
  }
};

run();
```

### System

- Node.js version: 16.3.1
- NPM version: 8.1.2
- Strapi version: 4.0.4
- Database: sqlite
- Operating system: Mac OS

**Comment by soupette** [comment]
We check with @Elhebert and the issue is coming from the naming of the controller in the content type builder. Renaming it should fix the issue.

**Comment by twobyte** [comment]
Dear @soupette, how do we rename the controller as you suggest? 
I am also seeing this same issue error when trying to build Gatsby:

`[2022-05-13 12:37:13.158] http: GET /api/content-type-builder/content-types (3 ms) 403
[2022-05-13 12:37:13.161] http: GET /api/content-type-builder/components (2 ms) 403`

Confusingly, `gatsby develop` works fine, but `gatsby build` does not. They are both using the same STRAPI_TOKEN and STRAPI_API_URL.

I am using Node v16.5.0, Strapi v4.1.10, Gatsby v4.13.1 and Yarn v1.22.17.

Would really like to get this static build deployed but kinda stuck. 

Thanks

**Comment by cortopy** [comment]
@soupette what name should it be? I could submit PR

This has been tagged as severity low but it's actually stopping me from using gatsby with strapi

**Comment by Circle6** [comment]
I'm still getting this in July - this is pretty fundamental guys, I have loads of coding experience but little to no experience with gatsby/strapi and i can't get the starter project going to explore the product because of this.

This is not a good look for people's first exposure to the product

**Comment by mnsileoni** [comment]
Sorry to bother you, but I'm having this issue right now and couldn't fix it following Circle 6 post. Any idea? Thanks.

**Comment by innerdvations** [comment]
Verified that this is still a problem in Strapi 5 rc

The problem is that neither "read only" nor "full access" select the "content type builder" -> 'getContentTypes' permissions

Workaround until it is fixed is to use "custom" and add that permission.
