### ISSUE TITLE
Error when starting strapi: Cannot read properties of undefined (reading 'attributes')

### ISSUE THREAD

**Issue by DanielChappuis** [strapi/strapi#15610]
### Required System information

- Node.js version: 16.17.1
- NPM version: 8.15.0
- Strapi version: 4.4.0 and 4.6.0
- Database: mariadb:10.7.4
- Operating system: Linux Debian 4.19.194-3 (inside Docker container)

### Describe the bug

I had to shutdown Strapi and when I tried to restart it I got the following error:

```
[2023-01-27 13:37:12.003] debug: ⛔️ Server wasn't able to start properly.
[2023-01-27 13:37:12.005] error: Cannot read properties of undefined (reading 'attributes')
TypeError: Cannot read properties of undefined (reading 'attributes')
    at Object.getNonVisibleAttributes (/opt/node_modules/@strapi/utils/lib/content-types.js:69:11)
    at getNestedFields (/opt/node_modules/@strapi/admin/server/services/content-type.js:30:51)
    at /opt/node_modules/@strapi/admin/server/services/content-type.js:43:31
    at /opt/node_modules/lodash/lodash.js:928:11
    at /opt/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/opt/node_modules/lodash/lodash.js:3032:24)
    at /opt/node_modules/lodash/lodash.js:4936:18
    at baseReduce (/opt/node_modules/lodash/lodash.js:925:5)
    at Function.reduce (/opt/node_modules/lodash/lodash.js:9749:14)
    at getNestedFields (/opt/node_modules/@strapi/admin/server/services/content-type.js:32:12)
```

The error seems to be related to a **structure** type (model) in my Strapi instance because if I remove the `/opt/app/src/api/structure/` folder I can start Strapi without error. I am wondering if there is something wrong in the `/opt/app/src/api/structure/content-types/structure/schema.json` file. This file has the following content. Note that I have never edited this file by hand of course.

```
{
  "kind": "singleType",
  "collectionName": "structures",
  "info": {
    "singularName": "structure",
    "pluralName": "structures",
    "displayName": "Structure",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "Booths": {
      "type": "component",
      "repeatable": true,
      "component": "structure.booth"
    }
  }
}
```

I got this error when trying to migrate from v4.4.0 to v4.6.0 but also when I rolled back to 4.4.0 with a backup. It's like the issue has been created while Strapi was running but I only got the error once I restarted it.

**Comment by joshuaellis** [comment]
I've had this a few times, I think the DX could be better around this in terms of error messages to help people.

**Comment by derrickmehaffy** [comment]
Yeah it's usually when a relation is defined but the other side is missing (eg if you manually build the relation in the schema).

I've been meaning to talk to the docs team too to build a list of common errors and what the issue is/how to fix it.

**Comment by DanielChappuis** [comment]
I am not sure what you mean by "manually build the relation in the schema" but for sure we have never edited the schema.json file manually. We have only started an instance of Strapi and only made changes using the web interface.

Do you know how can I recover from this issue because I am not currently able to start this instance of Strapi properly because of this error?

**Comment by shaikfareed46** [comment]
I was facing a issue similar to this while doing quick start

i was getting error

`Cannot read properties of undefined (reading 'addBreadcrumb')`

using 

`npx create-strapi-app@latest my-project --quickstart`

but solved using

`npx create-strapi-app@experimental`

Hope this will help people solve the issue

**Comment by minhphung210** [comment]
same issues . i try  `npx create-strapi-app@experimental` but not work

**Comment by soft4pilot** [comment]
Same problem!

**Comment by giancarlosxlr** [comment]
Same problem!

**Comment by mofodox** [comment]
Same problem here too!

I installed the latest node (v20.9.0) and it doesn't seem to work either. Please help!

**Comment by derrickmehaffy** [comment]
> Same problem here too!
> 
> I installed the latest node (v20.9.0) and it doesn't seem to work either. Please help!
> 
> I used both `npx create-strapi-app@experimental` and `npx create-strapi-app@latest my-project --quickstart`, still the issue persists:
> 
> ```
> Error while installing dependencies:
> npm WARN config production Use `--omit=dev` instead.
> npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
> npm WARN config `--include=optional` to include them.
> npm WARN config
> npm WARN config     Default value does install optional deps unless otherwise omitted.
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: next-reviews-cms@0.1.0
> npm ERR! Found: @strapi/strapi@0.0.0-experimental.e8b0ff5fe299b24567f51c4c8f17f5aa8bc9fb15
> npm ERR! node_modules/@strapi/strapi
> npm ERR!   @strapi/strapi@"0.0.0-experimental.e8b0ff5fe299b24567f51c4c8f17f5aa8bc9fb15" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @strapi/strapi@"4.0.0" from @strapi/plugin-users-permissions@0.0.0-experimental.e8b0ff5fe299b24567f51c4c8f17f5aa8bc9fb15
> npm ERR! node_modules/@strapi/plugin-users-permissions
> npm ERR!   @strapi/plugin-users-permissions@"0.0.0-experimental.e8b0ff5fe299b24567f51c4c8f17f5aa8bc9fb15" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR!
> npm ERR! For a full report see:
> npm ERR! /Users/tmka499c/.npm/_logs/2023-11-11T05_40_02_581Z-eresolve-report.txt
> 
> npm ERR! A complete log of this run can be found in: /Users/tmka499c/.npm/_logs/2023-11-11T05_40_02_581Z-debug-0.log
> TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
>     at /Users/tmka499c/.npm/_npx/363c03cf1fb7d8d1/node_modules/@strapi/generate-new/dist/utils/usage.js:36:31
>     at Array.forEach (<anonymous>)
>     at Module.captureStderr (/Users/tmka499c/.npm/_npx/363c03cf1fb7d8d1/node_modules/@strapi/generate-new/dist/utils/usage.js:35:37)
>     at createProject (/Users/tmka499c/.npm/_npx/363c03cf1fb7d8d1/node_modules/@strapi/generate-new/dist/create-project.js:133:17)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async createQuickStartProject (/Users/tmka499c/.npm/_npx/363c03cf1fb7d8d1/node_modules/@strapi/generate-new/dist/create-quickstart-project.js:18:3)
> ```

Your issue is entirely different and already solved in v4.15.4

**Comment by inspirezuza** [comment]
> Same problem here too!
> 
> I installed the latest node (v20.9.0) and it doesn't seem to work either. Please help!
> 
> I used both `npx create-strapi-app@experimental` and `npx create-strapi-app@latest my-project --quickstart`, still the issue persists:
> 
> ```
> Error while installing dependencies:
> npm WARN config production Use `--omit=dev` instead.
> npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
> npm WARN config `--include=optional` to include them.
> npm WARN config
> npm WARN config     Default value does install optional deps unless otherwise omitted.
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: next-reviews-cms@0.1.0
> npm ERR! Found: @strapi/strapi@0.0.0-experimental.e8b0ff5fe299b24567f51c4c8f17f5aa8bc9fb15
> npm ERR! node_modules/@strapi/strapi
> npm ERR!   @strapi/strapi@"0.0.0-experimental.e8b0ff5fe299b24567f51c4c8f17f5aa8bc9fb15" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @strapi/strapi@"4.0.0" from @strapi/plugin-users-permissions@0.0.0-experimental.e8b0ff5fe299b24567f51c4c8f17f5aa8bc9fb15
> npm ERR! node_modules/@strapi/plugin-users-permissions
> npm ERR!   @strapi/plugin-users-permissions@"0.0.0-experimental.e8b0ff5fe299b24567f51c4c8f17f5aa8bc9fb15" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR!
> npm ERR! For a full report see:
> npm ERR! /Users/tmka499c/.npm/_logs/2023-11-11T05_40_02_581Z-eresolve-report.txt
> 
> npm ERR! A complete log of this run can be found in: /Users/tmka499c/.npm/_logs/2023-11-11T05_40_02_581Z-debug-0.log
> TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
>     at /Users/tmka499c/.npm/_npx/363c03cf1fb7d8d1/node_modules/@strapi/generate-new/dist/utils/usage.js:36:31
>     at Array.forEach (<anonymous>)
>     at Module.captureStderr (/Users/tmka499c/.npm/_npx/363c03cf1fb7d8d1/node_modules/@strapi/generate-new/dist/utils/usage.js:35:37)
>     at createProject (/Users/tmka499c/.npm/_npx/363c03cf1fb7d8d1/node_modules/@strapi/generate-new/dist/create-project.js:133:17)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async createQuickStartProject (/Users/tmka499c/.npm/_npx/363c03cf1fb7d8d1/node_modules/@strapi/generate-new/dist/create-quickstart-project.js:18:3)
> ```

I encountered a similar issue, and it turned out that I hadn't updated my Node.js and npm versions as per the prerequisites mentioned [here](https://docs.strapi.io/dev-docs/quick-start)

I updated my Node.js and npm versions to align with the specified requirements, and it resolved the issue for me.

**Comment by gfargo** [comment]
Just encountered this issue when trying to run a transfer between sites.  Any news on providing more info on how to recover from this issue @derrickmehaffy?  Site transfer is entirely broken by an `undefined` variable 😞

**Comment by akki-akshat** [comment]
Even I am facing the same issue, any idea if I can go on a older version to resolve this?

**Comment by MrCaktuz** [comment]
Same issue still with :
`npx create-strapi-app@latest my-project --quickstart`.
It would be nice to have a previous version number that doesn't trigger this issue indeed.

**Comment by callmetuna** [comment]
i modified the schema and removed i18n  from plginOptions  = "pluginOptions": {
  }, and also changed from single type to collectionType on the last content type i created which solved the issue i manually rolled back last few changes and it worked

**Comment by alinoaimi** [comment]
I resolved the issue by upgrading my vps, from (512mb ram and 1vCPU) to (1gb ram and 1vCPU)

**Comment by JulianNymark** [comment]
Hello others! 👋  this was indeed a Memory limit issue for me. I was also using a 1Gb ram vps for my strapi test. There are two ways to go about fixing this issue afaik:

The minimum recommended Ram for Strapi as per their docs is 2Gb (https://docs.strapi.io/dev-docs/deployment)

## solution 1: Pay more
use an instance with minimum 2Gb ram, this one is the easiest.

## solution 2: use some of your diskspace as swap
follow these two steps on the CLI

1. Add a swap file to your system (I chose 2Gb, since then I know 2Gb swap + whatever actual RAM I have will be enough for this), full guide link is [here](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-20-04). These should be the minimum steps required to "get it working":
```
sudo fallocate -l 2G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
```

Confirm that the swap exists by running `htop` or `free -h`.

To make this change permanent (which you most likely will for a strapi install), follow the full guide above.

2. Tell node to _use_ more memory (when you install it node will not ask for more than your system ram, and if you don't have enough ram you'll get a heap out of memory issue). To do this run your strapi create command with the current environment variable:
```
NODE_OPTIONS="--max-old-space-size=2048" npx create-strapi-app@latest my-project --ts --no-run --quickstart
```

**Comment by smallfawn** [comment]
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
    at C:\Users\86056\AppData\Local\npm-cache\_npx\2d56dd13733e9da7\node_modules\@strapi\generate-new\dist\utils\usage.js:36:31
    at Array.forEach (<anonymous>)
    at Module.captureStderr (C:\Users\86056\AppData\Local\npm-cache\_npx\2d56dd13733e9da7\node_modules\@strapi\generate-new\dist\utils\usage.js:35:37)
    at createProject (C:\Users\86056\AppData\Local\npm-cache\_npx\2d56dd13733e9da7\node_modules\@strapi\generate-new\dist\create-project.js:133:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createQuickStartProject (C:\Users\86056\AppData\Local\npm-cache\_npx\2d56dd13733e9da7\node_modules\@strapi\generate-new\dist\create-quickstart-project.js:18:3)
    at async initProject (C:\Users\86056\AppData\Local\npm-cache\_npx\2d56dd13733e9da7\node_modules\create-strapi-app\dist\create-strapi-app.js:172:3)
PS C:\Users\86056\Desktop\CMS>



why？

v20.15.0
