### ISSUE TITLE
Concurrency bug when uploading files in parallel with API and "API Uploads" directory doesn't exist

### ISSUE THREAD

**Issue by marob** [strapi/strapi#16071]
### Required System information

- Node.js version: 18.12.1
- Strapi version: v4.7.1
- Database: PostgreSQL 14
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript: TS

### Describe the bug

When the "API Uploads" directory doesn't exist yet, if multiple file uploads are triggered simultaneously (in my case, it's through a migration script), the following error message appears in the logs (and some files are not uploaded):

```
 error: insert into "public"."upload_folders" ("created_at", "name", "path", "path_id", "updated_at") values ($1, $2, $3, $4, $5) returning "id" - duplicate key value violates unique constraint "upload_folders_path_id_index"
error: insert into "public"."upload_folders" ("created_at", "name", "path", "path_id", "updated_at") values ($1, $2, $3, $4, $5) returning "id" - duplicate key value violates unique constraint "upload_folders_path_id_index"
    at Parser.parseErrorMessage (/.../strapi-migration-test/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/.../strapi-migration-test/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/.../strapi-migration-test/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/.../strapi-migration-test/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

This is because multiple "API Uploads" directory creations are triggered in parallel.
When the "API Uploads" directory already exists, the problem doesn't occur.

To fix my migration script, I've uploaded the first file synchronously (to make sure the "API Uploads" directory creation is done only once), then I'm uploading the other files in parallel (by batches of 20).
With that behavior, the issue doesn't occur.

### Expected behavior

Concurrency issue should not happen.

**Comment by marob** [comment]
Note that there is a similar issue when creating multiple directories in parallel:

```
 error: insert into "public"."upload_folders" ("created_at", "created_by_id", "name", "path", "path_id", "updated_at", "updated_by_id") values ($1, $2, $3, $4, $5, $6, $7) returning "id" - duplicate key value violates unique constraint "upload_folders_path_id_index"
error: insert into "public"."upload_folders" ("created_at", "created_by_id", "name", "path", "path_id", "updated_at", "updated_by_id") values ($1, $2, $3, $4, $5, $6, $7) returning "id" - duplicate key value violates unique constraint "upload_folders_path_id_index"
    at Parser.parseErrorMessage (/.../strapi-migration-test/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/.../strapi-migration-test/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/.../strapi-migration-test/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/.../strapi-migration-test/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

I "fixed" that issue by creating directories in series instead of in parallel.

**Comment by marob** [comment]
@derrickmehaffy Can you please reopen that issue as it's not of the same type as https://github.com/strapi/strapi/issues/16363?

**Comment by joshuaellis** [comment]
Sorry Derrick has been away. I'm reading your issue and it's not very clear, could you add some simple reproduction steps that we could follow?

**Comment by marob** [comment]
To reproduce:
1. Start a Strapi on Postgre (no issue on sqlite)
2. Create the following `index.mjs` file:

```javascript
import {StrapiClient} from '@smile/strapi-client';
const strapiClient = new StrapiClient('http://127.0.0.1:1337', 'token', 'admin_token');
await Promise.all([
    strapiClient.createMediaFolder('Directory 1'),
    strapiClient.createMediaFolder('Directory 2'),
])
```

3. Replace:
- `'token'` with a valid Strapi token
- `'admin_token'` with a valid admin dashboard JWT token: you can get it easily with the following script in your browser's console when on Strapi admin UI: `JSON.parse(sessionStorage.jwtToken || localStorage.jwtToken)`
4. Download required dependency with `npm i @smile/strapi-client`
5. Run the script: `node index.mjs`

Only 1 directory should be created and an error should be displayed in Strapi logs.

You can also easily reproduce the issue for parallel upload of documents with the same script by replacing the folder creations by image uploads. You can use the [strapiClient.addMediaAsset(...)](https://github.com/Smile-SA/strapi-client#create-a-media) function for that.

I'm not using data-transfer.

**Comment by joshuaellis** [comment]
Thank you for the updates :)

**Comment by Marc-Roig** [comment]
Hello, I created a PR to prevent race conditions when creating folders, this should fix this issue.
https://github.com/strapi/strapi/pull/17146

I will be testing this during the week and also create an experimental releasae in case you want to try it out.

**Comment by Marc-Roig** [comment]
It worked in my machine, I created an experimental release: `0.0.0-experimental.e30dccd40a6b6f762843005e6baefe4f2f82d919`

If you have the chance , could you try it and see if it works for you? 🙏

**Comment by Marc-Roig** [comment]
I want to sort out some tests that are failing, but you shouldn't get any error when uploading multiple files at once now :)

**Comment by marob** [comment]
> It worked in my machine, I created an experimental release: `0.0.0-experimental.e30dccd40a6b6f762843005e6baefe4f2f82d919`
> 
> If you have the chance , could you try it and see if it works for you? 🙏

@Marc-Roig I updated to `0.0.0-experimental.e30dccd40a6b6f762843005e6baefe4f2f82d919` in `package.json` and installed, restarted and saw the corresponding version in Settings > Overview.
But this doesn't solve the issue, neither for parallel image upload nor parallel directory creation.

**Comment by Marc-Roig** [comment]
@marob thank you for testing this!! I will try replicating with your database and come up with a solution that works for you.

**Comment by marob** [comment]
@derrickmehaffy I don't see anything related to solving the concurrency bug.
Once again, this ticket is **not** related in any way to data transfer.
Please, reopen that issue.
