### ISSUE TITLE
Unnecessary warning for AWS S3 provider plugin

### ISSUE THREAD

**Issue by swapzone** [strapi/strapi#16360]
Good afternoon everyone,

I was stumbling across the following line of code:
https://github.com/strapi/strapi/blob/dec9156deac246d24ebb989c8c0cbf6e856fa331/packages/providers/upload-aws-s3/lib/index.js#L22

`legacyS3Options` will be an object and so this check will always be true. Shouldn't it better check for something like `Object.keys(legacyS3Options).length > 0`? Then we would not see the warning all the time without good reason.

**Comment by Marc-Roig** [comment]
Hello :) 
This should be fixed in https://github.com/strapi/strapi/pull/16323/files#diff-ce07d128a6bfc46461b45013da346cbd265761dd6e99e11fec52050ffe4d5665R49 
this will be released next week.

**Comment by swapzone** [comment]
Thanks for the info, Marc!

**Comment by aybasaran** [comment]
Hi There, Nothing changed?

**Comment by rafaelmelope** [comment]
@Marc-Roig the release is deployed? I updated the strapi version ans I still have the warning here.

**Comment by derrickmehaffy** [comment]
> @Marc-Roig the release is deployed? I updated the strapi version ans I still have the warning here.

No today's release was a hotfix, we do normal releases on Wednesdays

**Comment by kashif-ghafoor** [comment]
Any update on this issue. I am still getting warning
```
(node:216163) Warning: S3 configuration options passed at root level of the plugin's providerOptions is deprecated and will be removed in a future release. Please wrap them inside the 's3Options:{}' property.
```
strapi version: 2.18.1
provider-upload-aws-s3: ^4.15.0

**Comment by kashif-ghafoor** [comment]
Moing all configurations from providerOptions to seOptions solved the issue. Here is my working config which doesn't give warning,
```javsacript
{
    upload: {
      config: {
        provider: "aws-s3",
        providerOptions: {
          s3Options: {
            accessKeyId: env("AWS_S3_ACCESS_KEY_ID", ""),
            secretAccessKey: env("AWS_S3_SECRET_ACCESS_KEY", ""),
            region: env("AWS_S3_REGION", "us-east-1"),
            params: {
              Bucket: env("AWS_S3_BUCKET"),
              ACL: env("AWS_S3_ACL", "private"),
            },
            baseUrl: env("AWS_S3_CDN_URL"), // The base url to your CloudFront distribution
          },
        },
      },
    }
}
```

**Comment by kashif-ghafoor** [comment]
Adding above config stops warning. but plugin stops working this way.

**Comment by aybasaran** [comment]
> Moving all configurations from providerOptions to s3Options solved the issue. Here is my working config which doesn't give warning,
> 
> ```
> {
>     upload: {
>       config: {
>         provider: "aws-s3",
>         providerOptions: {
>           s3Options: {
>             accessKeyId: env("AWS_S3_ACCESS_KEY_ID", ""),
>             secretAccessKey: env("AWS_S3_SECRET_ACCESS_KEY", ""),
>             region: env("AWS_S3_REGION", "us-east-1"),
>             params: {
>               Bucket: env("AWS_S3_BUCKET"),
>               ACL: env("AWS_S3_ACL", "private"),
>             },
>             baseUrl: env("AWS_S3_CDN_URL"), 
>           },
>         },
>       },
>     }
> }
> ```

This is not working!!!!!!!!!!!!!!

**Comment by redondi88** [comment]
This fixed it for me:
```
s3Options:{
            credentials:{
              accessKeyId: env('AWS_ACCESS_KEY_ID'),
              secretAccessKey: env('AWS_ACCESS_SECRET'),
            },
            region: env('AWS_REGION'),
            params: {
              ACL: 'private', // <== set ACL to private
              signedUrlExpires: env('AWS_SIGNED_URL_EXPIRES', 60 * 60 * 24 * 7),
              Bucket: env('AWS_BUCKET'),
            },
          },```

**Comment by anuj-scanova** [comment]
The documentation itself does not reflect the valid configuration
https://github.com/strapi/strapi/tree/develop/packages/providers/upload-aws-s3

**Comment by Haxen2000** [comment]
> This fixed it for me:
> 
> ```
> s3Options:{
>             credentials:{
>               accessKeyId: env('AWS_ACCESS_KEY_ID'),
>               secretAccessKey: env('AWS_ACCESS_SECRET'),
>             },
>             region: env('AWS_REGION'),
>             params: {
>               ACL: 'private', // <== set ACL to private
>               signedUrlExpires: env('AWS_SIGNED_URL_EXPIRES', 60 * 60 * 24 * 7),
>               Bucket: env('AWS_BUCKET'),
>             },
>           },
> ```

This did it for me. I went from 
upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_ACCESS_SECRET'),
        region: env('AWS_REGION'),...

to
upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        s3Options: {
          credentials: {
            accessKeyId: env('AWS_ACCESS_KEY_ID'),
            secretAccessKey: env('AWS_ACCESS_SECRET'),
          },
          region: env('AWS_REGION'),...

Without the credentials, I had an additional error: `Credentials` passed directly to s3Options is deprecated`
