### ISSUE TITLE
Transfer feature hangs on asset transfer

### ISSUE THREAD

**Issue by bolg55** [strapi/strapi#16473]
### Required System information

- Node.js version: 16+
- NPM version: 8+
- Strapi version: 4.9.2
- Is your project Javascript or Typescript: JS

### Describe the bug

Edit: Based on issue #16437 this does not seem to be limited to cloud.

When attempting to transfer from a local Strapi instance to a Strapi Cloud project, using:

`yarn strapi transfer --to <url> --to-token <token> `
or
`npm run strapi transfer --to <url> --to-token <token>`

The transfer hangs when it gets to the `assets` transfer. Only killing the process will stop it, which then produces an error.

### Steps to reproduce the behavior

1. Go to a local Strapi project, running on 4.8+
2. Login to Strapi Cloud and ensure both local and cloud projects have same schema
3. Try to transfer from local to cloud using either:
`yarn strapi transfer --to <url> --to-token <token> `
or
`npm run strapi transfer --to<url> --to-token <token>`

### Expected behavior

That the transfer would go through successfully. 

### Screenshots

![image](https://user-images.githubusercontent.com/43022248/233807422-1f4baf7d-b5f0-45fd-923b-b8ceff93be50.png)

![image](https://user-images.githubusercontent.com/43022248/233736788-4105482f-aa10-4642-bbf9-2a829a6adc61.png)

**Comment by Boegie19** [comment]
@bolg55 issue seems also to be with --from from other hosts then strapi Cloud
https://github.com/strapi/strapi/issues/16437

**Comment by bolg55** [comment]
Updating name to reflect, thanks @Boegie19

**Comment by BorisKamp** [comment]
I can confirm I have the same problem, although it's from remote to local:

Im trying out the data transfer from my remote url (https://birdblocker-strapi.herokuapp.com/admin) to my local installation with `npm run strapi transfer -- --from https://birdblocker-strapi.herokuapp.com/admin`
After which I paste my transfer token which is of type `full access` with `unlimited` duration.

Both local and remote run Strapi `4.9.2`

My console gets stuck at this:
```
boriskamp@MacBook-Pro-2 birdblocker-strapi % npm run strapi transfer -- --from https://birdblocker-strapi.herokuapp.com/admin

> birdblocker-strapi@0.1.0 strapi
> strapi

? Please enter your transfer token for the remote Strapi source [hidden]
? The transfer will delete all the local Strapi assets and its database. Are you sure you want to proceed? Yes
(node:36287) Warning: S3 configuration options passed at root level of the plugin's providerOptions is deprecated and will be removed in a future release. Please wrap them inside the 's3Options:{}' property.
(Use `node --trace-warnings ...` to show where the warning was created)
```

It's been there for 10 minutes now. Who has a clue what's wrong here? How can I debug this?

My remote logs show nothing out of the ordinary either

**Comment by nagman** [comment]
I have the same problem. I've tried to downgrade strapi to 4.9.0 (with which it worked at the time) on both my local and remote instances, and it still didn't work.
I wonder if it's related to the data in the database, because it should work when downgrading (I've kept the same database for the downgraded version).
I even tried a transfer between two computers of the same local network, and it still hangs after the `Starting the compilation for TypeScript files in ...` line.

For now, the solution I've found is to `strapi export`, copy the exported file to the destination server, and then `strapi import`, but it's much more time consuming than just `strapi transfer`.

**Comment by ChrisCrossCrash** [comment]
I'm also having this exact problem, except I am trying to transfer to our own private server and not Strapi Cloud. Here is my terminal output when I try to transfer from my local computer to a remote server:

```bash
$ strapi transfer --to https://<site-redacted> --to-token <token-redacted>
? The transfer will delete all the remote Strapi assets and its database. Are you 
sure you want to proceed? Yes
Starting the compilation for TypeScript files in /home/<project-dir-redacted>
Starting transfer...
✔ entities: 1271 transfered (size: 2.3 MB) (elapsed: 24326 ms) 
⠼ assets: 22 transfered (size: 602 KB) (elapsed: 5 ms) (117.6 MB/s)^C
✖ assets: 22 transfered (size: 602 KB) (elapsed: 9307946 ms) 
```

It hung on that screen for about two hours before I finally gave up.

I also tried the `strapi export` feature. When I tried to `strapi import` the file in the docker container on our server. I let that run overnight but it hung on the `strapi import command`.

Some context that might be important:

- My local development computer is Ubuntu 20.04 on WSL in Windows 11.
- The project is in a Yarn Workspaces monorepo, so `node_modules` is two levels above where it normally would be.
- Our database is PostgreSQL (locally and on server)
- Development machine Node version 16.16.0
- Server Node version 16.20.0
- Strapi version 4.9.0 (local and server)
- Assets are hosted from AWS S3. Here is our `env/production/plugins.ts`:
  ```typescript
  export default ({ env }) => {
    return {
      upload: {
        config: {
          provider: 'aws-s3',
          providerOptions: {
            accessKeyId: env('AWS_ACCESS_KEY_ID'),
            secretAccessKey: env('AWS_ACCESS_SECRET'),
            region: env('AWS_REGION'),
            params: {
              Bucket: env('AWS_BUCKET'),
            },
          },
          actionOptions: {
            upload: {},
            uploadStream: {},
            delete: {},
          },
        },
      },
    }
  }
  ```

**Comment by derrickmehaffy** [comment]
Have been able to reproduce this on push/pull (get a bit farther on push but pulling just stalls out completely before it does anything) via Strapi cloud.

Raised to high based on other reports from cloud users + internal

**Comment by nagman** [comment]
I've update strapi to 4.10.1 and now the transfer reworks for me 🎉

**Comment by Marvv90** [comment]
New Release still not working for me ! Hangs on Transfer Assets !

**Comment by BorisKamp** [comment]
> I've updated strapi to 4.10.1 and now the transfer reworks for me 🎉

still broken on my installs on strapi `4.10.1`

**Comment by nagman** [comment]
Still not fixed with strapi `4.10.2`

**Comment by RafidMuhymin** [comment]
Downgrading to `v4.9.0`  from `v4.10.2` (and upwards) fixed the issue for both pulling and pushing (I didn't test if it was working in `v4.10.2`+).

**Comment by nagman** [comment]
I can confirm it still doesn't work with `4.10.4`

**Comment by TobsDev** [comment]
Experiencing the same issue (entities get transferred but assets hang) on v4.10.5. Is there any good workaround?

**Comment by Marvv90** [comment]
> Experiencing the same issue (entities get transferred but assets hang) on v4.10.5. Is there any good workaround?

Only Workaround for me - Import / Export Function

**Comment by nagman** [comment]
> Data loss when exporting / importing #16813

See that thread, because Import / Export is not 100% safe: https://github.com/strapi/strapi/issues/16813

**Comment by akerd** [comment]
I updated from 4.9.2 to 4.10.6 for both the local and remote environments and now the data transfer is initiated. Before it was stuck and didn't transfer anything, now entities are transferred.

But I have the same problem described by OP, the transfer is stuck at the assets step.

![2023-05-26 17_37_03](https://github.com/strapi/strapi/assets/1030305/9589d0f3-6005-415c-a5c8-0e7f090932ea)

**Comment by TobsDev** [comment]
> > Experiencing the same issue (entities get transferred but assets hang) on v4.10.5. Is there any good workaround?
> 
> Workaround for me - Import / Export Function

Even manual import / export partially fails to extend that it's impossible to tell what was transferred and what wasn't.

**Comment by phidah** [comment]
Works on v4.10.6 for me.

**Comment by KenMSK** [comment]
![Screenshot 2023-05-30 at 21 45 28](https://github.com/strapi/strapi/assets/51538854/532da76d-5918-401b-b158-8fdc754a1091)
It seems to always get stuck in the middle of the assets transfer.
Sometimes I can get it to go further to 48.4MB of data, but it still get stuck.
I have succeeded to transfer it before. But somehow it never succeed again.
running version 4.9.1

**Comment by SNPR** [comment]
I have the same problem with assets.
Strapi v4.10.7:

✔ entities: 19649 transfered (size: 138.6 MB) (elapsed: 287784 ms) 
⠦ assets: 13 transfered (size: 2.4 MB) (elapsed: 2 ms) (1.2 GB/s)

**Comment by shuffgy** [comment]
Subscribed here because it did not work for me but updated yesterday to the latest version `4.10.7` and `yarn strapi transfer --from` now worked for me (pulling all the data from production server to local)

**Comment by nagman** [comment]
I confirm that `yarn strapi transfer --from` still hangs on assets transfer with `4.10.7` (it stops at 32 assets transfered).

@shuffgy does your strapi have many assets to transfer?

**Comment by RafidMuhymin** [comment]
@nagman I was also facing the exact same issue with `v4.11.1`. Mine transfer was also stuck at the 32nd asset. But after 45-50s, the transfer resumed (or in other words, it took 45-50s for the 32nd asset to finish transferring).

It also should be noted that my speed was around 9MB/s. So, you might have to around 150-170s.

**Comment by Bassel17** [comment]
@RafidMuhymin Thank you, the fact that it resumed should be a good indication that the issue is fixed, that's we are waiting to see if the message failed before trying to send it again,

@nagman your issue seems to be more of a performance issue on the pull feature, we are aware of this and we will be working on fixing it  asap

**Comment by nagman** [comment]
I'm going to retry and I'll tell you :)

**Comment by beornf** [comment]
@RafidMuhymin The data loss when importing/exporting sounds like issue #16813. As a workaround I found downgrading to `v4.10.4` fixes both issues.

**Comment by nagman** [comment]
I can confirm it still doesn't work `with 4.11.4`.
Sometimes it hangs at 48 assets, sometimes 62, or 50, or 55...
And this is not a matter of performance as I let the script running during at least 10 minutes.
It would make sense if I had videos of 10GB, but I only have images - and the heaviest one weighs 26MB.

**Comment by RemiKalbe** [comment]
I'm also experiencing this issue, with 4.11.4!

Client:
```
✔ entities: 109 transfered (size: 156.3 KB) (elapsed: 2571 ms)
✖ assets: 32 transfered (size: 100.8 MB) (elapsed: 27031 ms)
[2023-07-10 16:30:36.663] error: [ERROR] WebSocket is not open: readyState 3 (CLOSED)
Transfer process failed.
```

Server:
```
2023-07-10T14:30:22.047 app[9080559f545018] cdg [info] Error [ERR_HTTP_REQUEST_TIMEOUT]: Request timeout
2023-07-10T14:30:22.047 app[9080559f545018] cdg [info] at new NodeError (node:internal/errors:399:5)
2023-07-10T14:30:22.047 app[9080559f545018] cdg [info] at onRequestTimeout (node:_http_server:787:30)
2023-07-10T14:30:22.047 app[9080559f545018] cdg [info] at Server.checkConnections (node:_http_server:600:7)
2023-07-10T14:30:22.047 app[9080559f545018] cdg [info] at listOnTimeout (node:internal/timers:569:17)
2023-07-10T14:30:22.047 app[9080559f545018] cdg [info] at process.processTimers (node:internal/timers:512:7)
```

**Comment by erinnovations** [comment]
same here for 4.11.4

**Comment by dligthart** [comment]
Similar issue here:

strapi.js transfer --from *** --from-token ***

Hangs 

⠹ entities: 4323 transfered (size: 3.5 MB) (elapsed: 87227 ms) (41.6 KB/s)[2023-07-20 11:08:53.955] http: GET index.html (3 ms) 200
⠋ entities: 4323 transfered (size: 3.5 MB) (elapsed: 87227 ms) (41.6 KB/s)[2023-07-20 11:09:24.058] http: GET index.html (3 ms) 200
⠇ entities: 4323 transfered (size: 3.5 MB) (elapsed: 87227 ms) (41.6 KB/s)[2023-07-20 11:09:54.159] http: GET index.html (2 ms) 200

**Comment by derrickmehaffy** [comment]
Media transfer should be fixed on v4.11.7 but we have another known issue with relations not being transferred properly that is being looked at.

**Comment by jbstewart** [comment]
I am getting this on Strapi 4.12.5 while transferring from my production instance to local.
I am using Cloudinary for assets.
First time I got the FATAL error "WebSocket is not open", now it just hangs.
It transferred the entities with no problem. But it hangs on the assets, even though it says there are 0 bytes to transfer.
Here's the output:
```
Starting the compilation for TypeScript files in /Users/me//strapi-repo
Starting transfer...
✔ entities: 20 transfered (size: 6.4 KB) (elapsed: 74 ms)
⠼ assets: 0 transfered (size: 0) (elapsed: 0 ms)
```
My command which I executed on my local machine was `strapi transfer --from https://mysite.com/admin --from-token xxxx --to-token yyyy --force`

**Comment by tomasIndicius** [comment]
Happening to me as well in `v.4.12.5`

**Comment by PeterBowater** [comment]
And here, v4.12.4

**Comment by jbstewart** [comment]
I should clarify that my situation turned out to be an error on my part - I did not realize that I had to create a separate Cloudinary account each for local, staging and production (well, you do on the free plan, since it only supports one environment). Since all three environments shared the same Cloudinary account, when it went to transfer assets, I believe it enumerated the assets to transfer, then deleted all the assets in the destination Cloudinary account, and then tried to copy all the assets enumerated in the first step, but because these files had just been deleted, it hangs. On the forums someone told me that all the Upload Providers will act this way, not just Cloudinary. The good news with Cloudinary was that on the website, buried in the fine print on some docs page, I found a statement recommending creating separate Cloudinary free accounts to support multiple environments, and they specifically said this was not disallowed on the free plan. You do need a separate email address for each Cloudinary account though.

**Comment by owentran** [comment]
I tried separating Cloudinary accounts with transfer (local, production) and it still hangs on assets transfer. 

BTW, I can get export/import to work correctly, so if it's the same mechanism as transfer, I believe it's something with the streaming download of assets. I'm on the latest version of strapi v4.12.7.

**Comment by derrickmehaffy** [comment]
> I tried separating Cloudinary accounts with transfer (local, production) and it still hangs on assets transfer. 
> 
> BTW, I can get export/import to work correctly, so if it's the same mechanism as transfer, I believe it's something with the streaming download of assets. I'm on the latest version of strapi v4.12.7.

It's most likely the other websocket connection issue we are seeing in slower or high latency connections

**Comment by sg-code** [comment]
I'm experiencing the same issue when attempting to push from local to remote (DigitalOcean App Platform [1GB RAM, 1vCPU]). My entire transfer file is ~8MB, and the request barely makes a blip in resource usage on the remote server.

The request timed out on the remote side after about two minutes:

```bash
[strapi] [2023-09-14 07:21:41] [2023-09-14 07:21:41.579] http: GET /dashboard/transfer/runner/push (11 ms) 200
[strapi] [2023-09-14 07:22:47] [2023-09-14 07:22:47.260] http: GET /admin/transfer/runner/push (21 ms) 404
[strapi] [2023-09-14 07:24:12] 
[strapi] [2023-09-14 07:24:12]   Error [ERR_HTTP_REQUEST_TIMEOUT]: Request timeout
[strapi] [2023-09-14 07:24:12]       at new NodeError (node:internal/errors:405:5)
[strapi] [2023-09-14 07:24:12]       at onRequestTimeout (node:_http_server:799:30)
[strapi] [2023-09-14 07:24:12]       at Server.checkConnections (node:_http_server:612:7)
[strapi] [2023-09-14 07:24:12]       at listOnTimeout (node:internal/timers:569:17)
[strapi] [2023-09-14 07:24:12]       at process.processTimers (node:internal/timers:512:7)
[strapi] [2023-09-14 07:24:12] 
```

Meanwhile the local transfer script keeps chugging along (hung up on 7.5MB of assets transfer). I let the local script do it's thing for ~20 minutes before I manually aborted the transfer.

**Comment by yvokeller** [comment]
Same issue here on the newest version of Strapi, v4.14.4. Transfer gets stuck at the 32nd asset, while the request times out after two minutes on the --from Strapi instance.

<img width="1728" alt="SCR-20231012-qikv" src="https://github.com/strapi/strapi/assets/22744751/d3b62d9e-6c8a-4a75-a28f-8fccf44ca248">

**Comment by alborq** [comment]
Same issues here on a latest version on strapi cloud. 
Maybe a @moderator can re-open issues

**Comment by chrisli-sas** [comment]
Still experiencing the same issue on v4.15.4

**Comment by yvokeller** [comment]
> Same issue here on the newest version of Strapi, v4.14.4. Worked when media library was file system based in both instances, now failing with a self-hosted S3 MinIO instance configured in the target system. Transfer gets stuck at the 32nd asset, while the request times out after two minutes on the source (--from) Strapi instance.
> 
> 
> 
> <img width="1728" alt="SCR-20231012-qikv" src="https://github.com/strapi/strapi/assets/22744751/d3b62d9e-6c8a-4a75-a28f-8fccf44ca248">
> 
> 

Same here 4.15.4. Transfer of assets still gets stuck at the 32nd one, but the HTTP Timeout is gone.

**Comment by Yuniac** [comment]
So what's the solution? I can't pull my data from remote to local in the tutorial using strapi cloud as remote

**Comment by jatin-accedo** [comment]
Is there an update on this issue? I have been facing the same issue trying to transfer from local to remote.

**Comment by Boegie19** [comment]
@Yuniac @jatin-accedo If both instances are on the latest version of strapi then please open a new issue about this if no open issue already exists.

**Comment by derrickmehaffy** [comment]
Reopening this as we got another report in TID4648 running 4.20.5

**Comment by xytis** [comment]
While investigating similar issue in my deployment, I discovered the following:

WebSocket timeout on the remote side does not produce any error on the receiving side, which appears as a "transfer hang".

The only indication of WebSocket closure on the remote side is such message:
```
[Data transfer] Restoring http timeouts
```

Note: my deployment uses an extra balancer in front of Strapi process, which was terminating the long lived http connection.

**Comment by cgraf-spiria** [comment]
We had entries in the `files` database table but the actual file was missing from the `uploads` folder.
When doing a transfer, it would hang around 2 minutes at `assets` .
Then is continues but without transfering anything: `assets: 0 transfered (size: 0) (elapsed: 0 ms)`
No errors/messages on either side.

After fixing the missing files it transfered correctly.

**Comment by derrickmehaffy** [comment]
> cc: @derrickmehaffy, @hanpaine 

Please open a new issue
