### ISSUE TITLE
400 error on Strapi data transfer

### ISSUE THREAD

**Issue by mpuxted** [strapi/strapi#16565]
### Required System information

- Node.js version: v16.20.0 (local and remote)
- NPM version: v8.19.4
- Strapi version: v4.10.1 (local and remote)
- Database: Postgres (remote) --- sqlite (local)
- Operating system: MacOS 13.3.1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

My remote instance is hosted in Google App Engine

Doing a remote transfer (I've tried **to** remote and **from** remote) results in a `error: [FATAL] Unexpected server response: 400`

My transfer token is correct and a full-access token.

To avoid doubt I've tried a regenerating the access token too. 

I've checked the logs in GCP for the remote instance and I can see nothing relevant.

I've tried: 

`strapi transfer --to https://cms--------.ew.r.appspot.com/admin --to-token .....`

and

`strapi transfer --from https://cms----------.ew.r.appspot.com/admin --from-token ......`

<img width="903" alt="image" src="https://user-images.githubusercontent.com/54951494/235185098-4f7cb22c-ea34-4d18-9da4-ede7f6eeadeb.png">

A log file is generated when it fails but unfortunately it contains no additional information - just: 
`[FATAL] Unexpected server response: 400`

I'm aware of [this issue](https://github.com/strapi/strapi/issues/16473) about the transfer hanging on assets, but my transfer doesn't even get that far so I believe it is a different issue.

**Comment by santiagoavilez** [comment]
I'm currently having a similar issue. I deployed my app to railway, and I'm trying to transfer the data from production to local.
The error response is not very useful either.
Both my local app and remote app have: strapi v4.9.0 and node v18.16.0

![image](https://user-images.githubusercontent.com/90413630/235766870-ea334ce7-efbf-449a-bc27-d9552a857be9.png)

**Comment by cclegg** [comment]
I'm also having an issue doing a pull transfer from remote to local, both on v4.10.2

The command just hangs on the local machine:
![image](https://user-images.githubusercontent.com/12034179/236063682-3e80e668-3ffe-46c9-bbad-51c7673a343b.png)

I'm happy to do some testing or help out in some way :-)

**Comment by ianyoung** [comment]
I'm experiencing the same issue from Production (Railway hosted) to local (Docker). I get the following connection error:

```
? Please enter your transfer token for the remote Strapi source [hidden]
? The transfer will delete all the local Strapi assets and its database. Are you sure you
 want to proceed? Yes
Error: connect ETIMEDOUT ::1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '::1',
  port: 5432
}
```
I've updated to the latest version 4.10.5 to be sure it's not something that's been fixed already. However, I still get the same error. Both deployments running Postgres.

**Comment by derrickmehaffy** [comment]
They should be fixed shortly we have several pull requests that are currently in the process of being reviewed before merge and release.

**Comment by JohnGale87** [comment]
Is there a release version you are targeting for having these issues resolved?

**Comment by derrickmehaffy** [comment]
> Is there a release version you are targeting for having these issues resolved?

Most likely 4.11.x scheduled for June 7th

**Comment by marcoautiero** [comment]
@ianyoung are you also having a 400 error like the author of this issue?

@santiagoavilez @cclegg are you still encountering the same issue in the most recent versions of Strapi?
If the error code or the characteristics of the issue are different from the one described here, please, can you open a dedicated issue with detailed information about your system and the steps to reproduce it? Differently, it would be hard to address them

**Comment by innerdvations** [comment]
I believe all of these issues have been solved in the past two months since the issue was reported, but there is not enough information to know if we are testing the exact cases reported.

I will leave this open for now until it is closed automatically, in case anyone is able to provide instructions to reproduce in the latest version.

**Comment by mpuxted** [comment]
Hi @innerdvations , no worries. I'll close this issue down. 
We implemented our own data transfer script before the general fixes to your data transfer so we haven't needed to use this feature again yet. Our data transfer gives us more flexibility, allowing us to choose which tables are transfered, so I don't think we need this anymore :)

**Comment by santiagoavilez** [comment]
> I believe all of these issues have been solved in the past two months since the issue was reported, but there is not enough information to know if we are testing the exact cases reported.
> 
> I will leave this open for now until it is closed automatically, in case anyone is able to provide instructions to reproduce in the latest version.



> @ianyoung are you also having a 400 error like the author of this issue?
> 
> @santiagoavilez @cclegg are you still encountering the same issue in the most recent versions of Strapi? If the error code or the characteristics of the issue are different from the one described here, please, can you open a dedicated issue with detailed information about your system and the steps to reproduce it? Differently, it would be hard to address them

I'm sorry for the late response, I fixed the issue with a workaround via a script. But this fix will help me a lot for future migrations/ syncs with my local environment
