### ISSUE TITLE
Upload plugin extension never loads

### ISSUE THREAD

**Issue by danwritecode** [strapi/strapi#16680]
### Required System information
- Node.js version: 16.18.0
- NPM version: 9.6.2
- Strapi version: 4.10.4
- Database: sqlite
- Operating system: Ubuntu on WSL
- Is your project Javascript or Typescript: Both (plugin extension seems to have to be JS otherwise you get a million TS errors)

### Describe the bug
I want to extend the Upload plugin. I created a folder at: ./src/extensions/upload with the file "strapi-server.js" within it (full path: ./src/extensions/upload/strapi-server.js). 

My objective with this extension is to override the "formatFileInfo" function so that I can give the filename my own name (a GUID). 

Contents of strapi-server.js: 
```javascript
const { v4: uuidv4 } = require('uuid');

module.exports = (plugin) => {
  plugin.services.upload.formatFileInfo = async function ({ filename, type, size }, fileInfo = {}, metas = {}) {
    console.log("custom formatFileInfo function invoked")
    const fileService = getService('file');

    let ext = path.extname(filename);
    if (!ext) {
      ext = `.${extension(type)}`;
    }
    const guidName = `${uuidv4()}.${ext}`;
    const basename = path.basename(guidName, ext);

    const entity = {
      name: guidName,
      alternativeText: fileInfo.alternativeText,
      caption: fileInfo.caption,
      folder: fileInfo.folder,
      folderPath: await fileService.getFolderPath(fileInfo.folder),
      hash: generateFileName(basename),
      ext,
      mime: type,
      size: bytesToKbytes(size),
    };

    const { refId, ref, field } = metas;

    if (refId && ref && field) {
      entity.related = [
        {
          id: refId,
          __type: ref,
          __pivot: { field },
        },
      ];
    }

    if (metas.path) {
      entity.path = metas.path;
    }

    if (metas.tmpWorkingDirectory) {
      entity.tmpWorkingDirectory = metas.tmpWorkingDirectory;
    }

    return entity;
  }

  return plugin;
};
```

However I am not seeing this function ever get invoked. There is no indication ever in the console that anything is happening with this extension.

### Steps to reproduce the behavior

1. Create a file at "./src/extensions/upload/strapi-server.js" and extend the extension per the documentation found [here](https://docs.strapi.io/dev-docs/plugins-extension)
2. Start the strapi server
3. Upload a file (and see nothing change)

### Expected behavior
I expect a few things: 
1. For the server to give me some sort of indication that my extension has been registered
2. If my extension fails to register, that I receive an error indication as much
3. That my extension gets invoked per how the documentation describes it should

### Additional context
I deleted .cache, dist, node_modules, yarn.lock; upgrade to latest strapi version, reinstalled all packages and restarted server to no avail.

**Comment by danwritecode** [comment]
For added context I went into node_modules directly and found the services/upload file that I'm attempting to extend and modified the formatFileInfo function directly with the exact code that I referenced above and it changes the filename to a guid as I expected it to. So I'm certain that there isn't an issue with the code itself causing some sort of error.

**Comment by ProfXponent** [comment]
experiencing the same issue

mixed ts/js project running strapi@4.10.4 because its the only version I could get working with TS

seems like plugin extensions never register

**Comment by ProfXponent** [comment]
yeah I just cloned down the nextjs starter and plugin extension works fine there, must be an issue with TS projects

more than likely a tsconfig issue

**Comment by jbhammon** [comment]
Wanted to add in that I'm seeing this same error with a different strapi version:

### Required System information

Node.js version: 18.6.0
NPM version: 8.13.2
Strapi version: 4.11.3
Database: sqlite
Operating system: macOS
Is your project Javascript or Typescript: Also both, for same reasons as above

I'm hoping to extend something about the Upload plugin too, to check that users aren't uploading more than a certain number of files for an entry.

**Comment by srinimk** [comment]
Hi , May be it is too late, but thought of adding it as it would help others.
You need to notify the server that it should look for the file.
For example to override the default file  Format, you need to do this in the src/index.js  file

    strapi.services["plugin::upload.upload"].formatFileInfo =
      require(<YOUR FILE PATH>). formatFileInfo;

**Comment by Benman2005** [comment]
I don't think this works anymore in Strapi v5? i can't seem to override the upload plugin.. 😢 (to save with filename without random suffix)
Can anybody help how to do this for v5? @derrickmehaffy perhaps?

**Comment by derrickmehaffy** [comment]
> I don't think this works anymore in Strapi v5? i can't seem to override the upload plugin.. 😢 (to save with filename without random suffix)
> Can anybody help how to do this for v5? @derrickmehaffy perhaps?

I **strongly** advise you don't do that. That suffix is for duplicate protection and without it you will almost certainly run into data loss at some point.

**Comment by Benman2005** [comment]
Thx for responding! We understand the risk it brings but we chose this route for easy sourcing in files, links etc. We'll take the risk with possible duplication as before, bc this worked in v4. 
Either way, the solution from @srinimk above wont work, and keeps being overwritten by original strapi upload plugin. 
Is there currently a way to override the upload plugin or preferably the formatFileInfo part?

**Comment by derrickmehaffy** [comment]
Best way would be to find and override the specific service in the ./src/index.js

I haven't done it in upload but I created an example of this for users permissions:

https://github.com/strapi-support-demo-apps/strapi-example-v4-override-up-blocked-default/blob/main/src/index.js

In this case the service was simple enough I could just wrap the service and tweak the data but for the service you are gonna be modifying you'll have to copy the entire service.

---

I'll suffix this for others reading this thread to make it very clear:

IF YOU DO THIS you are intentionally going past a security implementation we have implemented and the chances of you breaking something, corrupting data, or having data loss is extremely high and you DO THIS AT YOUR RISK.

We will not be responsible for any corruption you get as a result of bypassing this and we STRONGLY ADVISE YOU DONT DO THIS.

We implemented that suffix for a reason

**Comment by Gods-Blessing** [comment]
@derrickmehaffy still unable to override the function,
`register({ strapi }) {
    strapi.services["plugin::upload.upload"].formatFileInfo =
    require("./extensions/upload/overrides").formatFileInfoOverride;
  },`
  
  `async function formatFileInfoOverride(
  { filename, type, size },
  fileInfo = {},
  metas = {}
) {
  const fileService = strapi.plugin("upload").service("file");

  let ext = path.extname(filename);

  if (!ext) {
    ext = `.${extension(type)}`;
  }
  const usedName = (fileInfo.name || filename).normalize();
  const basename = path.basename(usedName, ext);

  const entity = {
    ext,
    mime: type,
    hash: basename,
    name: usedName,
    folder: fileInfo.folder,
    caption: fileInfo.caption,
    alternativeText: fileInfo.alternativeText,
    size: Math.round((size / 1000) * 100) / 100,
    folderPath: await fileService.getFolderPath(fileInfo.folder),
  };

  const { refId, ref, field } = metas;

  if (refId && ref && field) {
    entity.related = [
      {
        id: refId,
        __type: ref,
        __pivot: { field },
      },
    ];
  }

  if (metas.path) {
    entity.path = metas.path;
  }

  if (metas.tmpWorkingDirectory) {
    entity.tmpWorkingDirectory = metas.tmpWorkingDirectory;
  }

  return entity;
}

module.exports = {
    formatFileInfoOverride
}  `


do let me know if i am doing something wrong

**Comment by Gods-Blessing** [comment]
> @derrickmehaffy Thx for responding! We understand the risk it brings but we chose this route for easy sourcing in files, links etc. We'll take the risk with possible duplication as before, bc this worked in v4. 
> Either way, the solution from @srinimk above wont work, and keeps being overwritten by original strapi upload plugin. 
> Is there currently a way to override the upload plugin or preferably the formatFileInfo part?

Hi , Did you get any solution for this?

Even I tried to override it but failed.

**Comment by Benman2005** [comment]
@Gods-Blessing , nope, but didn't have time to delve into the solution to replace the entire upload service. went back to v4 and can't migrate to 5 without this upload naming solution, since a lot of links on the site are depending on it. 
Opening the repo just now for going back to v4 giving me _strapi relation "admin_permissions_role_links_fk" already exists_ error 🤦 
so yaayyy..

**Comment by Benman2005** [comment]
@derrickmehaffy , I'm trying to upgrade to strapi v5 again, and tried replacing the service/plugin/formatFileInfo function in different ways, but it seems everything i do in register/bootstrap is being overwritten with the original code from upload plugin. Plus, the example you're giving is also from v4, no? I think something changed with v5, and now we can't extend/overwrite the upload plugin in register in index.js, even though when logging the service in bootstrap, it does show the edited/extended version. 
Also I don't think it helps to separately run build command or remove cache/node_modules, right?
What do you think we have to do?

**Comment by Gods-Blessing** [comment]
> @derrickmehaffy , I'm trying to upgrade to strapi v5 again, and tried replacing the service/plugin/formatFileInfo function in different ways, but it seems everything i do in register/bootstrap is being overwritten with the original code from upload plugin. Plus, the example you're giving is also from v4, no? I think something changed with v5, and now we can't extend/overwrite the upload plugin in register in index.js, even though when logging the service in bootstrap, it does show the edited/extended version. 
> Also I don't think it helps to separately run build command or remove cache/node_modules, right?
> What do you think we have to do? 

Actually I was able to resolve this but with a work around.
what I did was :
1. Made changes in the upload code in strapi node modules folder.
2. Created a patch of it.

(But still I had to downgrade the application because of its stability )

**Comment by IvanGrassoGX** [comment]
@Gods-Blessing @Benman2005  I'm having the same issue with Strapi v5. Did you manage to get this working somehow? I'm also looking to avoid adding the hash at the end of the file when uloaded. I'm using the @strapi/provider-upload-aws-s3 dependency. Any help is appreciated. Thank you

**Comment by nboyet** [comment]
Hello @IvanGrassoGX

Just fix it for me. Create a file  `./src/extensions/upload/strapi-server.ts`

Then, on `strapi-server.ts`, you can override the generateFileName : 
```ts
export default (plugin) => {
  plugin.services["image-manipulation"].generateFileName = (name) => name
}
``` 
Of course, if you have two documents with the same name, it will probably lead to unwanted events.

**Comment by Benman2005** [comment]
Brilliant! I was wondering why i missed this, but it seems they [fixed](https://github.com/strapi/strapi/pull/23669) this in june. Hurray! 
They put it in the image-manipulation service, even though file names are generated for other file types as well. But great, let's not mention that and keep things this way where it works for us 🤫 

@nboyet , i think i'll still add the slugify from the original code to keep out spaces and weirdness from file paths. Something like this should work:

```js
var slugify = require("@sindresorhus/slugify");

const nameToSlug = (
  name,
  options = {
    separator: "_",
    lowercase: false,
  },
) => slugify(name, options);

module.exports = (plugin) => {
  plugin.services["image-manipulation"].generateFileName = (name) =>
    nameToSlug(name);
  return plugin;
};
```

**Comment by ngotrongphuc** [comment]
> Hello [@IvanGrassoGX](https://github.com/IvanGrassoGX)
> 
> Just fix it for me. Create a file `./src/extensions/upload/strapi-server.ts`
> 
> Then, on `strapi-server.ts`, you can override the generateFileName :
> 
> export default (plugin) => {
>   plugin.services["image-manipulation"].generateFileName = (name) => name
> }
> Of course, if you have two documents with the same name, it will probably lead to unwanted events.

Thanks, I use this to disable thumbnail generation and it works

**Comment by IvanGrasso77** [comment]
@nboyet @Benman2005  Cool, thanks, guys.

Yes, this worked, but I still have two issues to resolve. One is when files with the same name are uploaded. I'm trying to add something like **_0**, **_1** to the end of the file name. Another difficult thing to do is to know if the file was uploaded using the normal upload process or through the Replace Media plugin. If it was uploaded through the Replace Media plugin, then the name should remain the same. I appreciate any idea. Thank you

**Comment by ngotrongphuc** [comment]
> [@nboyet](https://github.com/nboyet) [@Benman2005](https://github.com/Benman2005) Cool, thanks, guys.
> 
> Yes, this worked, but I still have two issues to resolve. One is when files with the same name are uploaded. I'm trying to add something like **_0**, **_1** to the end of the file name. Another difficult thing to do is to know if the file was uploaded using the normal upload process or through the Replace Media plugin. If it was uploaded through the Replace Media plugin, then the name should remain the same. I appreciate any idea. Thank you

I haven't tried but I have an idea for the auto-increment suffix. Before upload you can check if the file with that name exists by using this api `/api/upload/files?filters[name][$eq]=${encodeURIComponent(name)}`, then use variable `let number = 0`, if it exist then add `_{number}` after the name and check again, if still exists, increase number `number+=1` and try again, recursively. About discriminate between create and replace, i don't know but you can try somehow get the request header and look for its `method`, `POST` is create and `PUT` is update/replace
