### ISSUE TITLE
The Admin HomePage won't load after upgrading to 4.10.7

### ISSUE THREAD

**Issue by erinnovations** [strapi/strapi#16924]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.6.0
- Strapi version: 4.10.7
- Database: postgres
- Operating system: windows  / linux
- Is your project Javascript or Typescript: typescript

### Steps to reproduce the behavior

After upgrading to 4.10.7 the admin home page stopped loading. The sidebar flashes for a fraction of a second and a blank page show. See the screenshot for the console error message.

### Expected behavior

Home page loads fully.

### Screenshots

![image](https://github.com/strapi/strapi/assets/253455/4d628672-38a5-4166-9858-95c74e9fb8e1)

**Comment by joshuaellis** [comment]
Did you run yarn build after upgrading? Looks like you're expecting a hook we've replaced with something else iirc

**Comment by beeb** [comment]
Different error but I'm also not able to see the admin panel:

![image](https://github.com/strapi/strapi/assets/703631/387338c6-9703-4898-8581-2306290242b3)

I have completely deleted the build and cache folders and rebuilt but to no avail.

**Comment by erinnovations** [comment]
I am using npm and I think I tried npm i and also npm run build.

I had to remove the node_modules, clear cache, reinstall everything with npm i, rebuild the app, several times and once it resolved by magic.

**Comment by joshuaellis** [comment]
> Using pnpm if that makes a difference

We don't support pnpm fully at the moment because the cache directory inteferes, so hard to say.

**Comment by Gianfranco97** [comment]
> Different error but I'm also not able to see the admin panel:
> 
> ![image](https://user-images.githubusercontent.com/703631/243554948-387338c6-9703-4898-8581-2306290242b3.png)
> 
> I have completely deleted the build and cache folders and rebuilt but to no avail. Using pnpm if that makes a difference.
> 
> Downgrading to 4.10.1 solves the issue (version I was on before trying to update).

it works for me too by downgrading to version 4.10.1

**Comment by erinnovations** [comment]
we are not using pnpm here.

**Comment by minht11** [comment]
We are using Strapi inside monorepo with npm and still have the same exact issue..
