### ISSUE TITLE
Authentication 500 Internal Server Error returned instead of 400 Bad Request

### ISSUE THREAD

**Issue by edwinhaver** [strapi/strapi#17194]
### Required System information

- Node.js version: 18.6.1
- NPM version: 9.5.1
- Strapi version: 4.11.3
- Database: sqlite
- Operating system: macOS Monterey v12.6
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When authenticating with api/auth/local with an incorrect username or password, HTTP status 500 Internal server error is returned whereas in the console it shows a ValidationError: Invalid identifier or password. 

### Steps to reproduce the behavior

1. In Postman set up a POST request with the following URL: http://localhost:1337/api/auth/local
2. In the body section create the following JSON object: `{"identifier": "john.doe@example.com", "password": "password"}`
3. Click Send
5. See response

The response is 500 Internal Server Error.

```
{
    "data": null,
    "error": {
        "status": 500,
        "name": "InternalServerError",
        "message": "Internal Server Error"
    }
}
```

### Expected behavior

HTTP status 400 (Bad Request) should be returned with the following JSON object: `{message: "Identifier or password invalid"}`.

### Additional context

While debugging, I noticed the following:
1. It throws a ValidationError which extends the ApplicationError in plugin-user-permissions > server > controllers > auth.js
2. Then it is caught in the middleware strapi > lib > middlewares > body.js and re-thrown. Here the error is an instance of Error but I cannot see if it is an instance of ApplicationError or ValidationError as this is not available in body.js.
3. Then it is caught in the middleware strapi > lib > middlewares > errors.js but here the error is no longer an instance of ApplicationError and therefore the HTTP status is set to 500 in formatInternalError as a catch all status.

See also: https://forum.strapi.io/t/get-500-error-on-client-side-but-403-in-terminal-for-the-backend/14496/19

**Comment by inumaki** [comment]
Hi, @edwinhaver . If this issue still persists, could you please give me the opportunity to work on it?

**Comment by edwinhaver** [comment]
Hi @inumaki, The issue still persists. Would appreciate it very much if you could solve this.

**Comment by inumaki** [comment]
Sure @edwinhaver , you can assign this issue to me.

**Comment by edwinhaver** [comment]
@inumaki, I don't seem to have the permissions to assign issues.

**Comment by Eventyret** [comment]
@inumaki you can just make up a PR itself if you want to and submit it don't need to assignt he issue itself. Just reference it
as per [CONTRIBUTING](https://github.com/strapi/strapi/blob/main/CONTRIBUTING.md)
Currently trying to replicate this too.

**Comment by Eventyret** [comment]
@edwinhaver I can't replicate this, currently i'm running on the same version and I get a 400 error.
This was a brand new strapi project, nothing added except for an admin user.
![image](https://github.com/strapi/strapi/assets/977232/609cd140-fd33-4258-b803-99ce8e5b45ea)

**Comment by inumaki** [comment]
HI @edwinhaver , @Eventyret  , i am also not able to reproduce it , as it is giving me the expected output
![image](https://github.com/strapi/strapi/assets/69989774/114664b6-d31c-4ca7-a6d3-d8e4650a0ed6)

**Comment by faryar76** [comment]
we have this issue in our project for long time 


```

 "@strapi/strapi": "4.10.5",
 "@strapi/utils": "^4.10.5",


```

**Comment by derrickmehaffy** [comment]
Marking as closed as we need updated steps to reproduce or more information. Once more information is provided we can reopen.

**Comment by faryar76** [comment]
Hey there,

I encountered an error while trying to reproduce it, and it turns out that the issue lies with the "@strapi/plugin-users-permissions" package. The good news is that updating the package to version 4.11.5 should fix the problem.

To resolve this, simply add the following code to your project's dependencies:

```
"@strapi/plugin-users-permissions": "4.11.5"
```

**Comment by edwinhaver** [comment]
I did a fresh installation with the latest version (4.11.5) and this has resolved the issue.

**Comment by rouroumaki** [comment]
Not working for me in 4.12.1 but working in 4.12.0

**Comment by branislavballon** [comment]
Same issue using (typescript):
- Node: v18.16.1
- npm: 9.5.1
- OS: node:18-alpine

``` javascript
{
// package.json
    "@strapi/plugin-documentation": "4.12.1",
    "@strapi/plugin-i18n": "4.12.1",
    "@strapi/plugin-users-permissions": "4.12.1",
    "@strapi/provider-email-nodemailer": "4.12.1",
    "@strapi/strapi": "4.12.4"
//...
}
```

Strapi log:

```
strapi-backend  | [2023-08-15 10:47:15.760] error: Invalid identifier or password
strapi-backend  | ValidationError: Invalid identifier or password
strapi-backend  |     at Object.callback (/opt/node_modules/@strapi/plugin-users-permissions/server/controllers/auth.js:62:15)
strapi-backend  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
strapi-backend  |     at async returnBodyMiddleware (/opt/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
strapi-backend  |     at async policiesMiddleware (/opt/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
strapi-backend  |     at async /opt/node_modules/@strapi/strapi/lib/middlewares/body.js:58:9
strapi-backend  |     at async /opt/node_modules/@strapi/strapi/lib/middlewares/logger.js:9:5
strapi-backend  |     at async /opt/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
strapi-backend  |     at async cors (/opt/node_modules/@koa/cors/index.js:61:32)
strapi-backend  |     at async /opt/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
strapi-backend  |     at async session (/opt/node_modules/koa-session/index.js:41:7)
```

**Comment by ohbob** [comment]
The issue is still here. In hosted docker image you cannot auth via postman. 500.

**Comment by imcbv** [comment]
`npm install @strapi/utils@[version]` did the trick for me.
This should help avoid scenarios where different versions are installed as nested dependencies.

**Comment by ceilitellu777** [comment]
https://forum.strapi.io/t/get-500-error-on-client-side-but-403-in-terminal-for-the-backend/14496/27?u=cris_cirhuza   npm install @strapi/utils@[version] did the trick for me.

**Comment by pakoc** [comment]
The versions of these packages must be the same, for example:

```code 
@strapi/plugin-users-permissions: 4.25.2
@strapi/strapi: 4.25.2
@strapi/utils: 4.25.2
```
Keeping the versions consistent will ensure everything works correctly.
