### ISSUE TITLE
Single-Type can't be published after adding a new language

### ISSUE THREAD

**Issue by ZacharyChim** [strapi/strapi#17314]
### Required System information

- Node.js version: 18.15
- NPM version: 9.5
- Strapi version: 4.11.5
- Database: sqlite
- Operating system: ubuntu 22.04
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I’m using the internationalization plugin with 2 languages. Everything was fine until I added the third language from the Admin panel. In the Admin panel, everything works fine, I can add the language, and I can switch languages in Single type or Collection type and update the field in different languages. But when I click publish in Single Type, I got "warning: already published", but the Single Type shows "editing draft version" for that language. Things work fine for Collection.

When I use Postman to fetch the Single Type, I don't see the data in the new language.

### Steps to reproduce the behavior

1. I added 2 languages first with all the fields saved and published.
2. And then I realized I need a third language after I added the third language, the error occurred.

### Expected behavior

Single Type in the new language should be able to be published.

### Screenshots

<img width="971" alt="Screen Shot 2023-07-14 at 12 20 22 AM" src="https://github.com/strapi/strapi/assets/4985235/5dd17fde-e14d-4c26-8750-250122e832d5">

**Comment by derrickmehaffy** [comment]
Confirmed on v4.11.5. You have to publish the en one first, then try to create a new locale and save/publish:

![image](https://github.com/strapi/strapi/assets/8593673/a8e5846d-b456-465b-9d69-88f97a7fd9dd)

**Comment by ZacharyChim** [comment]
> 

That's what I did. I published EN first and then added a second language (saved and published, and everything was fine), finally, I added the third language, import every fields from the second language, saved (no problem), click publish, I got the warning (already published).

**Comment by derrickmehaffy** [comment]
Yeah I created the first entry before I added the other langs, added FR and ES, went back to create an ES entry to save/publish and hit it.

**Comment by ehsmsh** [comment]
It throws already.published error not matter the order of publishing different locales. I have two locales and only can publish one of them for single types. It is clearly a bug.

**Comment by ZacharyChim** [comment]
Any got any idea about what to do with it? Any workaround?

**Comment by ehsmsh** [comment]
As it is added as a high severity bug, should be solved in next release. For now, just downgrade to v4.11.4 and run "yarn build" to rebuild the admin panel and it works fine.

**Comment by ehsmsh** [comment]
> Any got any idea about what to do with it? Any workaround?

As it is added as a high severity bug, should be solved in next release. For now, just downgrade to v4.11.4 and run "yarn build" to rebuild the admin panel and it works fine.

**Comment by ZacharyChim** [comment]
<img width="851" alt="Screen Shot 2023-07-16 at 11 19 22 PM" src="https://github.com/strapi/strapi/assets/4985235/73efd908-48d2-4a5e-8229-32b2812590c7">
<img width="1155" alt="Screen Shot 2023-07-16 at 11 20 10 PM" src="https://github.com/strapi/strapi/assets/4985235/a97dd70f-5b42-46f6-af0a-dc5adbf0a916">

Downgraded to v4.11.4, still not working

**Comment by ehsmsh** [comment]
> <img width="851" alt="Screen Shot 2023-07-16 at 11 19 22 PM" src="https://github.com/strapi/strapi/assets/4985235/73efd908-48d2-4a5e-8229-32b2812590c7">
> <img width="1155" alt="Screen Shot 2023-07-16 at 11 20 10 PM" src="https://github.com/strapi/strapi/assets/4985235/a97dd70f-5b42-46f6-af0a-dc5adbf0a916">
> 
> Hi @ehsmsh, downgraded to v4.11.4, still not working

Rebuild the admin ui. I'm just working with it and it is fine.

**Comment by ZacharyChim** [comment]
> > <img alt="Screen Shot 2023-07-16 at 11 19 22 PM" width="851" src="https://user-images.githubusercontent.com/4985235/253812293-73efd908-48d2-4a5e-8229-32b2812590c7.png">
> > <img alt="Screen Shot 2023-07-16 at 11 20 10 PM" width="1155" src="https://user-images.githubusercontent.com/4985235/253812303-a97dd70f-5b42-46f6-af0a-dc5adbf0a916.png">
> > Hi @ehsmsh, downgraded to v4.11.4, still not working
> 
> Rebuild the admin ui. I'm just working with it and it is fine.

I did rebuild the admin UI, did not work for me.

**Comment by bhavesh-chaudhari** [comment]
I had the same issue, upgrading to 4.12.0 worked for me.

**Comment by alex-lechner** [comment]
This issue is either still not resolved or it has come back. I'm using Strapi v.4.17.1 (latest version as of now).

**Comment by lidachao111222** [comment]
v4.17.1 has the same issue...

**Comment by RyanHavoc** [comment]
I am also having this issue on the latest version.

**Comment by PeakVisionMedia-MW** [comment]
Same problem on the latest version v4.19.

**Comment by KostaDokosic** [comment]
same issue, latest version

**Comment by pierrejqs** [comment]
I am also having the same issue with the latest version

**Comment by nicolatournay** [comment]
Same issue on v4.19.1

**Comment by baileymatthewr** [comment]
Same issue on v4.20.3

**Comment by sc-robertvliek** [comment]
Same issue v4.20.4l, it saves the single type under the default locale in the database. No matter what locale is selected in the admin panel.

**Comment by fwax-pro** [comment]
The problem comes from database registration.
Strapi saves the data with the default locale.
Go to the database and edit the locale.

**Comment by leewallis** [comment]
> Same issue v4.20.4, it saves the single type under the default locale in the database. No matter what locale is selected in the admin panel.

Yep, I'm seeing this exact same thing. It's not great.

**Comment by meecrobe** [comment]
> Similar issue here (v4.20.3).
– If I fill-in default locale, save, and than fill-in another locale, the default locale gets overwritten, and the other locale is empty.
– If I save & publish default locale, than fill in another locale and try to publish, I get "Not found".

Can confirm on v4.21.0.

**Comment by florentbolo** [comment]
Similar on v4.21.1.
I fixed it by switching the another locale to default language, edit the single type in the new default locale, then switch again to the initial default language.Then I don't have the bug anymore. 
Hope it helps

**Comment by DasunEdirisinghe** [comment]
@florentbolo Thanks. It worked for me

**Comment by vovapankiw** [comment]
still does not work on 4.23.0
Yep we could use a workaround that [florentbolo](https://github.com/florentbolo) suggested, but it will be great to have a fix from Strapi itself

**Comment by rickgrade3** [comment]
My solution is to apply "yarn patch packages" with modification below (By add query params "locale=en" after "/publish").
/// index-8XZny-tn.js - line 6933
`
const getQs = ()=>{
        const ss = Object.fromEntries(new URLSearchParams((new URL(window.location.href)).search))
        if(ss['plugins[i18n][locale]']){
          return `?locale=${ss['plugins[i18n][locale]']}`
        }
        return ``
      }
      const { data: data2 } = await post(
        isSingleType ? `/content-manager/${collectionType}/${slug}/actions/publish${getQs()}` : `/content-manager/${collectionType}/${slug}/${id}/actions/publish${getQs()}`
      );
`
And I think that "/unpublish" on the same file should also send the parameter too.

Tested with 4.19.1.
