### ISSUE TITLE
Transfer between dockerized instances fails

### ISSUE THREAD

**Issue by 20x-dz** [strapi/strapi#17557]
### Required System information

Production/Staging:
- Node.js version: `v16.20.1`
- NPM version: `8.19.4`
- Strapi version: `4.12.1`
- Database: `mysql  Ver 15.1 Distrib 10.4.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`
- Operating system: `Ubuntu 22.04.2 (with Docker version 23.0.3, build 3e7cbfd)`
- Is your project Javascript or Typescript: JS

Local Env:
- Node.js version: `v16.14.2`
- NPM version: `8.12.2`
- Strapi version: `4.12.1`
- Database: `sqlite`
- Operating system: `MacOS 13.4.1`
- Is your project Javascript or Typescript: JS

### Describe the bug

Strapi transfer was fixed in v4.12.1. 🥳 

It worked perfectly to pull data from production (dockerized setup with mysql database) to a local dev environment (barebone node with sqlite). And it worked to push the same data from dev to staging (dockerized setup with mysql database).

But directly transfering between production and staging fails: 

```bash
? The transfer will delete all the local Strapi assets and its database. Are you sure you want to proceed? Yes
Starting transfer...
✔ entities: 811 transfered (size: 1.2 MB) (elapsed: 4946 ms)
⠧ assets: 1053 transfered (size: 73.7 MB) (elapsed: 30066 ms) (2.5 MB/s)/opt/node_modules/@strapi/data-transfer/dist/strapi/providers/remote-source/index.js:59
                    await this.writeAsync(assets[item.assetID].stream, chunk);
                                                               ^

TypeError: Cannot read properties of undefined (reading 'stream')
    at PassThrough.<anonymous> (/opt/node_modules/@strapi/data-transfer/dist/strapi/providers/remote-source/index.js:59:64)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I first tried to work around that by excluding the files first and then to try to move the files separately. Here it fails as well, but the error message is a little bit more descriptive:
```
me@staging:~$ docker compose exec -it strapi strapi transfer --from-token $TOKEN --from https://STRAPI/admin/ --force --only files
? The transfer will delete all the local Strapi assets and its database. Are you sure you want to proceed? Yes
Starting transfer...
✖ assets: 26 transfered (size: 303.9 KB) (elapsed: 28 ms)
[2023-08-02 23:16:14.677] error: [ERROR] Error while uploading asset logo_white_27348633e8.svg TypeError: Cannot set properties of null (setting 'url')
Transfer process failed.
```

Any ideas?

As mentioned before, I was able to transfer the data from production to staging via my local dev environment.

### Steps to reproduce the behavior

Not sure if this can be reproduced on a clean instance. I'll gladly add some debug statements if that helps.

### Expected behavior

Transfer should work.

**Comment by stijnbe** [comment]
I'm seeing the same error (Cannot set properties of null (setting 'url')) exporting and importing assets locally. I debugged the data-transfer code a bit and found out that the metadata is sometimes corrupt. There is a comma in the hash and the url that was not there. Also when I check the json metadata within the archive it looks fine. Only when the tar package loads the metadata file then the comma is there.

Strapi version: 4.12.1

packages/core/data-transfer/src/strapi/providers/local-destination/index.ts:309
```
const entry: IFile = await strapi.db.query('plugin::upload.file').findOne({
              where: { hash: uploadData.hash },
            });
entry.url = uploadData.url;
```

uploadData (notice the , in Fran,cisco20 in the hash and url)
```
 {
  id: 5518,
  name: 'Outsite20San20Francisco20Mission2014_opt.jpeg',
  alternativeText: null,
  caption: null,
  width: 1000,
  height: 1500,
  formats: {
    thumbnail: {
      ext: '.jpeg',
      url: 'https://cdn.outsite.co/cms/thumbnail_Outsite20_San20_Francisco20_Mission2014_opt_ee3e297f70.jpeg',
      hash: 'thumbnail_Outsite20_San20_Francisco20_Mission2014_opt_ee3e297f70',
      mime: 'image/jpeg',
      name: 'thumbnail_Outsite20San20Francisco20Mission2014_opt.jpeg',
      path: null,
      size: 3.78,
      width: 104,
      height: 156
    }
  },
  hash: 'Outsite20_San20_Fran,cisco20_Mission2014_opt_ee3e297f70',
  ext: '.jpeg',
  mime: 'image/jpeg',
  size: 138.91,
  url: '/uploads/Outsite20_San20_Fran,cisco20_Mission2014_opt_ee3e297f70.jpeg',
  previewUrl: null,
  provider: 'aws-s3',
  provider_metadata: null,
  folderPath: '/19/113/114',
  createdAt: '2023-08-07T19:16:20.308Z',
  updatedAt: '2023-08-07T19:16:20.321Z',
  stream: Readable...
}
```


chunk.metadata
```
{
  id: 5518,
  name: 'Outsite20San20Francisco20Mission2014_opt.jpeg',
  alternativeText: null,
  caption: null,
  width: 1000,
  height: 1500,
  formats: {
    thumbnail: {
      ext: '.jpeg',
      url: 'https://cdn.outsite.co/cms/thumbnail_Outsite20_San20_Francisco20_Mission2014_opt_ee3e297f70.jpeg',
      hash: 'thumbnail_Outsite20_San20_Francisco20_Mission2014_opt_ee3e297f70',
      mime: 'image/jpeg',
      name: 'thumbnail_Outsite20San20Francisco20Mission2014_opt.jpeg',
      path: null,
      size: 3.78,
      width: 104,
      height: 156
    }
  },
  hash: 'Outsite20_San20_Fran,cisco20_Mission2014_opt_ee3e297f70',
  ext: '.jpeg',
  mime: 'image/jpeg',
  size: 138.91,
  url: 'https://cdn.outsite.co/cms/Outsite20_San20_Francisco20_Mission2014_opt_ee3e297f70.jpeg',
  previewUrl: null,
  provider: 'aws-s3',
  provider_metadata: null,
  folderPath: '/19/113/114',
  createdAt: '2023-08-07T19:16:20.308Z',
  updatedAt: '2023-08-07T19:16:20.321Z'
}
```

Actual metadata json file in the tar file
```
{
  "id": 5518,
  "name": "Outsite20San20Francisco20Mission2014_opt.jpeg",
  "alternativeText": null,
  "caption": null,
  "width": 1000,
  "height": 1500,
  "formats": {
    "thumbnail": {
      "ext": ".jpeg",
      "url": "https://cdn.outsite.co/cms/thumbnail_Outsite20_San20_Francisco20_Mission2014_opt_ee3e297f70.jpeg",
      "hash": "thumbnail_Outsite20_San20_Francisco20_Mission2014_opt_ee3e297f70",
      "mime": "image/jpeg",
      "name": "thumbnail_Outsite20San20Francisco20Mission2014_opt.jpeg",
      "path": null,
      "size": 3.78,
      "width": 104,
      "height": 156
    }
  },
  "hash": "Outsite20_San20_Francisco20_Mission2014_opt_ee3e297f70",
  "ext": ".jpeg",
  "mime": "image/jpeg",
  "size": 138.91,
  "url": "https://cdn.outsite.co/cms/Outsite20_San20_Francisco20_Mission2014_opt_ee3e297f70.jpeg",
  "previewUrl": null,
  "provider": "aws-s3",
  "provider_metadata": null,
  "folderPath": "/19/113/114",
  "createdAt": "2023-08-07T19:16:20.308Z",
  "updatedAt": "2023-08-07T19:16:20.321Z"
}
```

**Comment by stijnbe** [comment]
I found a way to fix this, by not using minipass from the tar package. However I have no idea what's causing the way minipass reads the stream to corrupt the json in this way. 

packages/core/data-transfer/src/file/providers/source/index.ts:283
```
//const content = await entry.collect();
const chunks = [];
for await (const data of entry) chunks.push(data);
const content = Buffer.concat(chunks);
```

**Comment by 20x-dz** [comment]
Maybe @derrickmehaffy can shed some light on this? 😅

**Comment by jackyang-patreon** [comment]
https://github.com/strapi/strapi/pull/17831 linking this here as this is a similar issue

**Comment by felthy** [comment]
I'm the author of #17831, yes this looks like the exact problem I've fixed in that PR.

**Comment by mauriciabad** [comment]
Same error here

**Comment by millsoft** [comment]
I just encountered the same problem but with the import. I get a different error if I use strapi transfer (see below)
Strapi V4.13.2
Files are stored on a S3 bucket.


```
strapi import --force --file /tmp/restore/280c1a3736884287949b61d97b5c5c3f48675df3/strapi_export.tar
? The import will delete your existing data! Are you sure you want to proceed? Yes
Starting the compilation for TypeScript files in /opt/app
Starting import...
✔ entities: 1041 transfered (size: 2.3 MB) (elapsed: 13831 ms)
⠏ assets: 228 transfered (size: 44.6 MB) (elapsed: 40936 ms) (1.1 MB/s)[2023-10-06 08:45:34.992] error: [ERROR] Error while uploading asset 1200px_Logo_svg_300x164_7cf85cba86.png TypeError: Cannot set properties of null (setting 'url')
⠋ assets: 229 transfered (size: 44.6 MB) (elapsed: 41047 ms) (1.1 MB/s)Import process failed.
error Command failed with exit code 1.
```

and strapi transfer looks like this:

```
strapi transfer --force --from https://strapi.mydomain.com/admin --from-token=MYTOKEN
? The transfer will delete all the local Strapi assets and its database. Are you sure you want to proceed? Yes
Starting the compilation for TypeScript files in /opt/app
Starting transfer...
[2023-10-06 08:53:27.797] error: [FATAL] WebSocket is not open: readyState 3 (CLOSED)
Transfer process failed.
error Command failed with exit code 1.
```

the websocket error appears after a minute or so. Probably this is the same cause like in strpai import.

**Comment by 20x-dz** [comment]
I just wanted to close this, because I was able to transfer from my production instance to my local env just fine (the assets, mind you, see #19113), but when trying this out this error sadly still occurs. But at least I am able to shed a little bit more light to it, it seems to be pull related, because pushing (only the assets!) worked just fine:

```
user@host:~/strapi$ docker compose exec strapi npm run strapi transfer -- --to https://strapi.example.com/admin/ --to-token $TOKEN --only files --force

> lo-rem-ip-sum@0.1.0 strapi
> strapi transfer --to https://strapi.example.com/admin/ --to-token IAMNOTATOKEN --only files --force

? The transfer will delete existing data from the remote Strapi! Are you sure you want to proceed? Yes
DEBUG: Detected Strapi version 4.15.5 for interface building
INFO: schemas-to-ts plugin's acceptedNodeEnvs property does not include 'production' environment. Skipping conversion of schemas to Typescript.
[2023-12-22 19:25:53.230] warn: (Schema Integrity) block.swipe-page does not exist on source
? There are differences in schema between the source and destination, and the data listed above will be lost. Are you sure you want to continue? Yes
Starting transfer...
✔ assets: 1718 transfered (size: 142.2 MB) (elapsed: 50118 ms)
┌──────────┬───────┬───────────────┐
│ Type     │ Count │ Size          │
├──────────┼───────┼───────────────┤
│ assets   │  1718 │     142.2 MB  │
├──────────┼───────┼───────────────┤
│ -- .JPG  │    10 │ (     1.5 MB) │
├──────────┼───────┼───────────────┤
│ -- .jpeg │   107 │ (     6.6 MB) │
├──────────┼───────┼───────────────┤
│ -- .jpg  │  1219 │ (    70.6 MB) │
├──────────┼───────┼───────────────┤
│ -- .pdf  │     1 │ (   102.1 KB) │
├──────────┼───────┼───────────────┤
│ -- .png  │   243 │ (    63.1 MB) │
├──────────┼───────┼───────────────┤
│ -- .svg  │   138 │ (   403.9 KB) │
├──────────┼───────┼───────────────┤
│ Total    │  1718 │     142.2 MB  │
└──────────┴───────┴───────────────┘
Transfer process has been completed successfully!
```

Pulling otoh…

```
⠙ assets: 456 transfered (size: 33.5 MB) (elapsed: 13272 ms) (2.5 MB/s)/opt/node_modules/@strapi/data-transfer/dist/index.js:2836
          await this.writeAsync(assets[item.assetID].stream, chunk);
                                                     ^

TypeError: Cannot read properties of undefined (reading 'stream')
    at PassThrough.<anonymous> (/opt/node_modules/@strapi/data-transfer/dist/index.js:2836:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.19.0
```

**Comment by a-schaefers** [comment]
Any chance you recently switched away from the S3 provider

**Comment by a-schaefers** [comment]
> Any chance you recently switched away from the S3 provider

@20x-dz or any chance your production deploy is using the s3 provider, and you're pulling down to local?

I think S3 exif metdata is handled much differently on S3 (non-posix conformant) and might be what is going on here. Could be why push works. And I'm not familiar enough with strapi internals, but I suspect strapi is looking for metadata it just can't find (due to s3 quirks). Any devs in here?

Thanks

**Comment by 20x-dz** [comment]
@a-schaefers Thank you for your question. Our files are stored on a regular linux filesystem (`/dev/sda1 on / type ext4 (rw,relatime)`) mounted as a docker volume in the container.

**Comment by escii** [comment]
any progress or idea on this?

`yarn strapi transfer --from https://example.dev/admin --from-token TOKEN`

Strapi version: 4.24.0
The server I am pulling from is a Kubernetes cluster with CephFS.
It was working before for a while.. only a few more pictures got added and I did run `npm update` on both sides.
```
✔ entities: 147 transfered (size: 141.4 KB) (elapsed: 173 ms)
⠴ assets: 217 transfered (size: 40.9 MB) (elapsed: 13425 ms) (3.1 MB/s)C:\Users\Alice\Documents\GitHub\example-strapi\node_modules\@strapi\data-transfer\dist\index.js:2914
          await this.writeAsync(assets[item.assetID].stream, chunk);
                                                     ^

TypeError: Cannot read properties of undefined (reading 'stream')
    at PassThrough.<anonymous> (C:\Users\Alice\Documents\GitHub\example-strapi\node_modules\@strapi\data-transfer\dist\index.js:2914:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.10.0
error Command failed with exit code 1.
```
Thanks

**Comment by midnightdim** [comment]
I'm experiencing a very similar issue:

```
Starting transfer...
✔ entities: 459 transfered (size: 1005.1 KB) (elapsed: 3469 ms)
⠦ assets: 236 transfered (size: 19.3 MB) (elapsed: 7657 ms) (2.5 MB/s)/site/node_modules/@strapi/data-transfer/dist/index.js:2914
          await this.writeAsync(assets[item.assetID].stream, chunk);
                                                     ^

TypeError: Cannot read properties of undefined (reading 'stream')
    at PassThrough.<anonymous> (/site/node_modules/@strapi/data-transfer/dist/index.js:2914:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.20.0
```

It happens when I attempt to pull the data from one Linux instance to another, and it happens at the same asset (after transferring 236 assets).
However, when I pull the data from a Windows box, this particular issue doesn't happen (sometimes it fails with a timeout error, but that's a different issue).

**Comment by jimwib** [comment]
I am having the same issue with transferring files, it does only seem to be happening with files over 1mb - here is another git issue with the same problem for everyone's reference https://github.com/strapi/strapi/issues/20087

**Comment by kovacsgergelydpr** [comment]
Hi Guys,

I've run into the same or similar issue and investigated a bit. I have transferred large (>1mb) image files between strapi instances.
My test results are:
1. strapi export in a docker container -> copy tar.gz file into another docker container -> strapi import - WORKS
2. strapi transfer (pull) from a docker container into a local barebone instance -> then strapi transfer (push) from local into a docker container - WORKS
3. strapi transfer (pull) directly from a docker container into an other docker container - CORRUPTED FILES
4. strapi transfer (push) directly from a docker container into an other docker container -WORKS

"pull" means: the transfer was running on the destination instance and "push" means on the source instance.

Based on the results, i think the problem will be somewhere around the  local-destination provider and only occures in case of a docker container based destination instance.

I hope it helps, thanks!

**Comment by innerdvations** [comment]
This was fixed with https://github.com/strapi/strapi/pull/25177 and https://github.com/strapi/strapi/pull/23479 -- can't reproduce in the latest Strapi version (docker to docker transfers succeed since 5.43.0).

Closing unless someone has a recent reproduction.
