### ISSUE TITLE
Data transfer transfer websocket connection dies due to memory leak

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#17749]
### Required System information

- Node.js version: v18
- NPM version: v9
- Strapi version: v4.12.5 (though various versions in v4.12.x)
- Database: SQLite, PG, MySQL, MariaDB
- Operating system: Linux Mint 21.2
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When executing a transfer (regardless of push/pull) at some point the websocket connection may die (latency, network outage, ect) and the transfer will stall and fail with similar though not exact errors.

From TID4618
```
error: [ERROR] WebSocket is not open: readyState 3 (CLOSED)
Transfer process failed.
```

From TID4617
```
Starting transfer...
✔ entities: 701 transfered (size: 661.4 KB) (elapsed: 825 ms)
✔ assets: 570 transfered (size: 51.2 MB) (elapsed: 3676 ms)
✖ links: 1047 transfered (size: 209.3 KB) (elapsed: 15374 ms)
[2023-08-21 18:01:51.209] error: [ERROR] WebSocket is not open: readyState 3 (CLOSED)
Transfer process failed.
```

From TID4602
![image](https://github.com/strapi/strapi/assets/8593673/31a8a04e-5183-4385-8651-75d59ed8dfe8)

### Steps to reproduce the behavior

Reproducing is quite difficult, it appears related to high network latency or a spotty internet connection. So far the support team has not been able to reproduce.

### Expected behavior

If the websocket connection temp breaks we should re-establish the the connection and continue the transfer

### Screenshots

N/A

### Code snippets

N/A

### Additional context

Related to the following Internal TID:
- 4617
- 4618
- 4602

(There are more but will add them as we find them)

Most likely related to https://github.com/strapi/strapi/issues/14417 or a new memory leak. Effectively the asset transfer causes a memory leak that leads to the destination server running out of memory and crashing/restarting which terminates the websocket connection.

**Comment by derrickmehaffy** [comment]
I have confirmed the issue based on the amount of tickets we have open right now. I still haven't been able to reproduce.

**Comment by derrickmehaffy** [comment]
Currently we have 9 tickets related to this issue, here is the full list I could quickly locate:

- 4619
- 4618
- 4617
- 4602
- 4565
- 4526
- 4525
- 4496
- 4477

**Comment by web-admin** [comment]
Same here... Data Transfer works perfect on small size database. If db is bigger then my connection is broken while transferring assets. I was trying to transfer assets only but I got the same result.

**Comment by tomasIndicius** [comment]
Happening to me as well with a ~300 MB `assets` folder.

**Comment by PeterBowater** [comment]
And here, v4.12.4, importing from Strapi cloud to local instance

Not sure how big asset folder is (as on Strapi cloud), always stops around 81 seconds on the elapsed timer, ~84 seconds in the whole process while it handshakes and opens the websocket etc.

I am running it with --force and --from-token to speed that side of it up.

**Comment by PeterBowater** [comment]
To add, is there any verbose logging we can switch on?

**Comment by web-admin** [comment]
I was playing with Knex "pool" settings and mainly increased "**acquireTimeoutMillis**" time to 600000ms. Unfortunately, the connection has been closed at similar time as before - just after 300000ms as below:

```
Starting transfer...
⠴ entities: 6884 transfered (size: 4.5 MB) (elapsed: 318522 ms) (14.3 KB/s)/home/projects/cms-headless/strapi-v1/node_modules/knex/lib/client.js:312
        convertedError = new KnexTimeoutError(
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
...
```

**Comment by derrickmehaffy** [comment]
Adding to this (from TID4664) not all the issues are just related to the websockets but generic timeouts either in the database or via Axios:

```
Error: AxiosError: timeout of 30000ms exceeded

    at RedirectableRequest.handleRequestTimeout (-snipped-/node_modules/axios/dist/node/axios.cjs:3047:16)

    at RedirectableRequest.emit (node:events:511:28)

    at Timeout.<anonymous> (-snipped-/node_modules/follow-redirects/index.js:169:12)

    at listOnTimeout (node:internal/timers:573:17)

    at process.processTimers (node:internal/timers:514:7) {

  code: 'ECONNABORTED',

  config: {

    transitional: {

      silentJSONParsing: true,

      forcedJSONParsing: true,

      clarifyTimeoutError: false

    },

    adapter: [ 'xhr', 'http' ],

    transformRequest: [ [Function: transformRequest] ],

    transformResponse: [ [Function: transformResponse] ],

    timeout: 30000,

    xsrfCookieName: 'XSRF-TOKEN',

    xsrfHeaderName: 'X-XSRF-TOKEN',

    maxContentLength: -1,

    maxBodyLength: -1,

    env: { FormData: [Function], Blob: [class Blob] },

    validateStatus: [Function: validateStatus],

    headers: AxiosHeaders {

      Accept: 'application/json, text/plain, */*',

      Authorization: 'Bearer -snipped-',

      'Content-Type': 'multipart/form-data; -snipped-',

      'User-Agent': 'axios/1.4.0',

      'Content-Length': '2510986',

      'Accept-Encoding': 'gzip, compress, deflate, br'

    },

    method: 'post',

    url: '-snipped-.strapiapp.com/api/upload',
    ```

**Comment by derrickmehaffy** [comment]
Providing an updated list of internal Tickets related to this issue:

- 4664
- 4648
- 4643
- 4618
- 4617
- 4602
- 4565
- 4526
- 4525
- 4496
- 4477
- 4153

If you are a customer of Strapi Cloud or Strapi enterprise and you do not see your ticket in this list, please send an email to support@strapi.io so we can properly track the issue. Note that ONLY Strapi Cloud or Strapi Enterprise should use this email address, community questions WILL NOT be answered via that email address.

If you were directed here from a ticket, we will be using this issue to handle notification to all impacted users due to the volume of tickets.

Thanks

**Comment by jackyang-patreon** [comment]
I can very consistently reproduce the
```
error: [ERROR] WebSocket is not open: readyState 3 (CLOSED)
Transfer process failed.
```
message. Happy to provide more details on my setup/how I run into this if it's helpful to the team!

**Comment by derrickmehaffy** [comment]
> I can very consistently reproduce the
> 
> ```
> error: [ERROR] WebSocket is not open: readyState 3 (CLOSED)
> Transfer process failed.
> ```
> 
> message. Happy to provide more details on my setup/how I run into this if it's helpful to the team!

Yes please, specifically if you are able to reproduce in a fresh project between two local instances!

**Comment by jackyang-patreon** [comment]
The case I have handy is between a local instance + a matching server instance (deployed via k8s):

On my server logs that I'm trying to pull from, I see
```
  Error [ERR_HTTP_REQUEST_TIMEOUT]: Request timeout      at new NodeError (node:internal/errors:405:5)      at onRequestTimeout (node:_http_server:799:30)      at Server.checkConnections (node:_http_server:612:7)      at listOnTimeout (node:internal/timers:569:17)      at process.processTimers (node:internal/timers:512:7)
```
And on the client which I'm receiving I get the logs referenced above
```
error: [ERROR] WebSocket is not open: readyState 3 (CLOSED)
Transfer process failed.
```

One thing to note is that this transfer does involve files/assets that are not local uploads but from a S3-esque provider and that anecdotally most times the transfer for the entities themselves complete but get hung up while starting the files/assets step

**Comment by austinnebel** [comment]
This might be related to https://github.com/strapi/strapi/issues/17891#issue-1876369599, in which the `error: [ERROR] WebSocket is not open: readyState 3 (CLOSED)` error is caused by the destination instance crashing due to an out-of-memory error.

**Comment by derrickmehaffy** [comment]
> This might be related to https://github.com/strapi/strapi/issues/17891#issue-1876369599, in which the `error: [ERROR] WebSocket is not open: readyState 3 (CLOSED)` error is caused by the destination instance crashing due to an out-of-memory error.

Now that is interesting and very possible. I haven't seen this for our cloud users as we should normally be able to detect if the cloud instance ran OOM and crashed/restarted but certainly isn't entirely out of the equation.

**Comment by tomasIndicius** [comment]
Is there an alternative way for Strapi Cloud users to transfer content? This issue is holding us from releasing a project for a client.

**Comment by jackyang-patreon** [comment]
Thanks @derrickmehaffy ! For the first item

> Currently no there is not (unless you create a script to run normal POST requests against the content-types but that is a bit much for most).

Does there happen to be a reference for doing something similar that we can look at?

**Comment by tomasIndicius** [comment]
Hi @marcoautiero is there any updates on this issue? It's preventing us from releasing a big project for a client :/

**Comment by alexbudin** [comment]
@derrickmehaffy  I have 4.13.5 on a local Strapi and 4.13.5 on our enterprise cloud strapi and we have the same issue when trying to transfer.

On the cloud side we get this error:

<img width="1655" alt="image" src="https://github.com/strapi/strapi/assets/832030/7855b137-014b-4cae-9e70-2170d1c2ec0d">


And in the terminal, on the local side we get this:

<img width="794" alt="image" src="https://github.com/strapi/strapi/assets/832030/f6a316b2-cb2c-464b-90a2-0187facb7177">

After we get the Starting transfer... message, it hangs for a minute and then the error is thrown.


We tried to downgrade to version 4.11.4 on the local version and on the Cloud one and we got the transfer to work:

<img width="1714" alt="image" src="https://github.com/strapi/strapi/assets/832030/ee79144d-3147-4e0f-9509-a328e337057c">

but it failed because of a query error. Have no idea why. but clearly the files have been transferred. Unfortunately because of the error, of course they were not available in the media library.

For who is reading this, seems the transfer works for CONTENT but not for FILES.

When we use the  **--only files** parameter it fails, but  **--only content** manages to transfer the content but not the files. So if you dont have a lot of files, you can then upload them manually.

I really hope this helps someone until this is fixed entirely.

Thank you.

**Comment by derrickmehaffy** [comment]
Thank you for the information cc @Bassel17

**Comment by alexbudin** [comment]
@derrickmehaffy 

I just tested with the latest release **4.13.6**: https://github.com/strapi/strapi/releases/tag/v4.13.6

and its the same error on the local version and the same on the cloud enterprise one (i attempted 2 transfer commands with the **--only files** parameter):

<img width="883" alt="image" src="https://github.com/strapi/strapi/assets/832030/8a778630-2be0-4da8-9784-8bd68fd1085b">

The total size of the assets for my test is around 44MB.

Any idea when this will be addressed? as its impacting our enterprise cloud instance and we cannot go live with a project because of this error and its becoming quite a big business issue.

Thank you.

**Comment by Bassel17** [comment]
@alexbudin we are looking in to this, we managed to reproduce this and will be working on a fix as soon as we can.
thank you for the info provided

**Comment by alexbudin** [comment]
> @alexbudin we are looking in to this, we managed to reproduce this and will be working on a fix as soon as we can. thank you for the info provided

That is indeed amazing news! If there is anything else i can help with, let me know

**Comment by alexbudin** [comment]
Because this is critical for us to be fixes as soon as possible, today i did 2 other tests, thinking that maybe it got fixed

I got this error: 

<img width="1093" alt="image" src="https://github.com/strapi/strapi/assets/832030/2fdf7d76-d362-40ac-a2c1-d34a5390099a">


and then the second time i did i got this error:

<img width="708" alt="image" src="https://github.com/strapi/strapi/assets/832030/8d24cb46-2714-4b78-9736-0f3bb4ddef06">

Just thought i leave this here.

Is there a timeline for this fix that maybe it can be pushed for the cloud instances so we can transfer files?

Thank you.

**Comment by derrickmehaffy** [comment]
They are actively working on it for sure, a timeline isn't possible but I'd say at a maximum by the end of the month. Generally it should be sooner than that but depends on how complex the issue is.

**Comment by alexbudin** [comment]
@derrickmehaffy @Bassel17 any updates on this issues?

**Comment by alexbudin** [comment]
Seems that version 4.13.7 has the same issues:

<img width="922" alt="image" src="https://github.com/strapi/strapi/assets/832030/dec6cec8-0b9b-47be-9b75-18505b7918be">


<img width="910" alt="image" src="https://github.com/strapi/strapi/assets/832030/365c177a-ddb8-4cb0-8c26-93a55917ebf9">

**Comment by derrickmehaffy** [comment]
The DX squad has been able to reproduce the issue and currently still working on trying to find a solution. I got an update today internally from @marcoautiero that it is still WIP and is a bit more challenging to solve then previously believed. We don't have an ETA for the moment.

**Comment by alexbudin** [comment]
@derrickmehaffy and how are paying enterprise cloud owners supposed to transfer their files and data to be able to use the service? Is there any workaround ?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy and how are paying enterprise cloud owners supposed to transfer their files and data to be able to use the service? Is there any workaround ? 

Currently no but trust me that is a particularly common point of internal discussion. I'm following the topic internally closely.

**Comment by indit0m** [comment]
I was able to go around this issue by connecting Strapi to an external database, and using an S3 Bucket to serve the images. A bit slow but seems to work so far.

**Comment by derrickmehaffy** [comment]
Hey everyone here, just a heads up we believe we have isolated the cause and are testing/qa'ing a fix right now that will resolve the issue (we do plan an additional enhancement PR later). I'm currently generating an experimental release for this that I'll share after but we expect (hope) this to make it into Wednesday's release of v4.14.1 or at the latest v4.14.2 next week.

**Comment by derrickmehaffy** [comment]
Here is the experimental version for anyone who wishes to test: `0.0.0-experimental.7a78d05d61d6a236a8f2f71201d490c4961c411d`

Typical warning here, we do not advocate for anyone to use experimental versions in any production setting. You do so at your own risk.

**Comment by PeterBowater** [comment]
To clarify, will this work as the receiving instance or do we need the host instance or both to be updated?

**Comment by derrickmehaffy** [comment]
> To clarify, will this work as the receiving instance or do we need the host instance or both to be updated? 

Most likely just the receiving end but it will probably need to be done on both.

Basically the root cause of the issue was a change made in Node 18 to set the default HTTP time out, we noticed for the web sockets that timeout was set to 60 seconds, The bulk of this change basically just goes in and disables that time out during the transfer.

This means both the primary web socket and all of the requests for file uploads to external providers will have their HTTP timeouts set to unlimited during the transfer.

In the future will add a configuration option to allow the user to set their own specific time out if they don't want it to run constantly

**Comment by derrickmehaffy** [comment]
You'll hit a database timeout issue though for anything longer than 6 minutes due to the default Knex/tarn database pulling timeout options. For the vast majority of users this shouldn't be a concern as the transfer shouldn't take longer than 6 minutes, and that one can be worked around directly by configuring the time out within tarn

**Comment by derrickmehaffy** [comment]
Reopening as users will still get the issue due to a memory leak that's unrelated to the original version of this

**Comment by alexbudin** [comment]
@derrickmehaffy 

Tested with 4.14.3 and its the exact ssame issue.

I have updated the local Strapi and the enterprise cloud one to the latest version, generated a new transfer token, executed the transfer command and i get this:

<img width="1075" alt="image" src="https://github.com/strapi/strapi/assets/832030/600a3360-248d-4ca8-9aa4-be4d02a25351">

and the logs on the Cloud version:

<img width="1103" alt="image" src="https://github.com/strapi/strapi/assets/832030/b6ea7329-54f2-4f63-825d-3e9bb60e987d">

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy 
> 
> Tested with 4.14.3 and its the exact ssame issue.
> 
> I have updated the local Strapi and the enterprise cloud one to the latest version, generated a new transfer token, executed the transfer command and i get this:
> 
> <img width="1075" alt="image" src="https://github.com/strapi/strapi/assets/832030/600a3360-248d-4ca8-9aa4-be4d02a25351">
> 
> and the logs on the Cloud version:
> 
> <img width="1103" alt="image" src="https://github.com/strapi/strapi/assets/832030/b6ea7329-54f2-4f63-825d-3e9bb60e987d">
> 

Yeah we know, the error is the same but the cause isn't basically we've found a memory leak on the destination while uploading the media files which causes the destination to crash and restart which closes the websocket. We are trying to determine exactly where that memory leak is and see if we can fix it.

**Comment by Boegie19** [comment]
is this issue only on spesific OS's since if it is could be that you send more then 1 image to sharp at the time that would cause it to leak memory ??

**Comment by derrickmehaffy** [comment]
> is this issue only on spesific OS's since if it is could be that you send more then 1 image to sharp at the time that would cause it to leak memory ??

We haven't tested much but it's reproducable on Linux and that makes up like 90% of our usage including Strapi Cloud.

**Comment by Boegie19** [comment]
then there is a big chance it is connected to https://github.com/strapi/strapi/issues/14417

**Comment by derrickmehaffy** [comment]
> then there is a big chance it is connected to https://github.com/strapi/strapi/issues/14417

Exactly, that's what the DX squad is currently looking into and as a bonus if we can fix that issue and this one at the same time.

**Comment by Boegie19** [comment]
@alexbudin until the issue is closed you can expect it to not work in feture versions.

**Comment by alarner** [comment]
Thanks for working on fixing this. In the mean time is there a recommended work-around?

**Comment by Boegie19** [comment]
downgrade to version 4.11.4

**Comment by truemythgames** [comment]
any updates ? How can we transfer our data to another environment ? Is there a way to have access to the database? Please help! I'm paying for cloud and i cannot trust that the data will be usable if i cannot transfer them !

**Comment by derrickmehaffy** [comment]
> any updates ? How can we transfer our data to another environment ? Is there a way to have access to the database? Please help! I'm paying for cloud and i cannot trust that the data will be usable if i cannot transfer them ! 

It's being worked on, there aren't other ways at the moment that you can do yourself.

If you absolutely immediately need your data, contact the support team and they can get you a raw database dump once or twice (it's not something we will do regularly for you).

**Comment by derrickmehaffy** [comment]
I'm locking this issue from further comment. When the issue is resolved then this issue will be closed and have a linked PR.

We are actively working on this issue and it is not a simple fix. We understand how important this issue is but we want to ensure we fix it properly.

**Comment by derrickmehaffy** [comment]
Small update here but with some very good news.

Currently we have two PRs that are being heavily tested and QA'ed at the moment that will hopefully solve this issue:

- https://github.com/strapi/strapi/pull/18599
- https://github.com/strapi/strapi/pull/18557

One small downside noticed for now is that the speed of the asset transfer has slowed down but previous "speed" looked to be fake as it was heavily overloading the destination to the point where the destination ran out of memory and crashed. We will evaluate speed improvements in the future but the most important part is stability in the transfer.

We don't quite have a timeline to get these merged yet as we want to put it through the paces of rigorous testing and QA to ensure this issue is solved once and for all. I will unlock this thread and allow comments however:

**IF YOU comment saying "this is still happening on v4.x.x" you will be temp banned. Until this issue is closed and the PRs merged AND released we know it's still happening. Anyone doing testing of experimentals is exempt from this.**

If someone does want to assist us with real-world testing by using an experimental, YOU DO SO AT YOUR OWN RISK, we cannot promise the experimentals will not completely mess up your data, so don't do it in production.

Current experimental version is: `0.0.0-experimental.c594d39bd99186eab7f05bd9517adc6704d3b1a2`
BOTH the source and destination need to be on this version to test properly

**Comment by derrickmehaffy** [comment]
Here is one of the QA runs I just did with no issues other than speed

![image](https://github.com/strapi/strapi/assets/8593673/01b1ae97-8641-4580-a251-47f27d9d79de)

**Comment by derrickmehaffy** [comment]
Good news here, we are slating to release the fix in v4.15.1 this Thursday (2023/11/2), transfer of assets will be slower but they will be much more stable.

Original root cause was a backpressure issue on the websockets where the source was sending the files too fast which lead to the destinations memory to be overloaded causing the destination to crash and break the websocket connection. By far this is one of if not the most complex bug we have ever had so I wanted to thank everyone who gave us their debug information, test projects, sample data sets, and all the info and sorry it took a while to find a proper fix but we wanted to do it right.

**Comment by alexbudin** [comment]
@derrickmehaffy This is good news. Cannot wait to finally be able to use the Cloud version of Strapi :)

**Comment by indit0m** [comment]
@derrickmehaffy I see `v.14.15.1` has been released-then-deprecated...Is any of the "several issues" you identified in your release related to the data-transfer? I tried `v.4.14.6` but I still get the websocket error (although much later in the process): 
<img width="1039" alt="image" src="https://github.com/strapi/strapi/assets/73914374/08af257e-38c0-4eb0-89e3-1d2d5d5bf054">

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I see `v.14.15.1` has been released-then-deprecated...Is any of the "several issues" you identified in your release related to the data-transfer? I tried `v.4.14.6` but I still get the websocket error (although much later in the process): 
> <img width="1039" alt="image" src="https://github.com/strapi/strapi/assets/73914374/08af257e-38c0-4eb0-89e3-1d2d5d5bf054">
> 

Where is the destination instance hosted and can you give some of the information (specs) of that?

**Comment by indit0m** [comment]
It's a Strapi Cloud account (https://vivid-prize-a0f7ef28c9.strapiapp.com/admin/)

**Comment by indit0m** [comment]
@derrickmehaffy It's a Strapi Cloud account (https://vivid-prize-a0f7ef28c9.strapiapp.com/admin/)

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy It's a Strapi Cloud account (https://vivid-prize-a0f7ef28c9.strapiapp.com/admin/)

Can you open a ticket with us

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy It's a Strapi Cloud account (https://vivid-prize-a0f7ef28c9.strapiapp.com/admin/)

I was able to grab the crash logs from your app and they are entirely different from this issue and not one we've seen before:

```
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: Error while uploading asset -snip-.webp Error: Transaction query already complete, run with DEBUG=knex:tx for more info
    at /home/app/node_modules/@strapi/data-transfer/dist/index.js:2131:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/app/node_modules/@strapi/data-transfer/dist/index.js:278:25
    at async /home/app/node_modules/@strapi/database/dist/index.js:6179:21
Emitted 'error' event on Writable instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.18.2
```

**Comment by christiancp100** [comment]
This PR fixed the issue: https://github.com/strapi/strapi/pull/18599

**Comment by poulato** [comment]
hi guys, i've been trying for weeks to manage a successful transfer and still no progress. I've tried to transfer from cloud to local -> getting error 504. I've tried from local strapi to other local strapi -> getting error : error: [FATAL] socket hang up . 
Strapi Version : 4.15.4
Being able to transfer data it's crucial for any project ! Please help, i cannot release the project without the ability to transfer data from stage to production

**Comment by alexbudin** [comment]
Same here. No idea how we can use the enterprise account when we cannot transfer files from one side to another. We've been switching and advising most of our clients to go with Digitalocean droplets and we are doing the transfers manually. If only we would have a simple way to put some files in a folder onto the cloud account, and just do all this manually somehow.

**Comment by alexbudin** [comment]
@derrickmehaffy Can you advise if we should open different ticket on here or still use this one as this one is marked as done.

Thank you.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Can you advise if we should open different ticket on here or still use this one as this one is marked as done.
> 
> Thank you.

New issue please, this issue was for the transfer pull memory leak which we have confirmed fixed. We knew that by fixing this one it's likely the transfer would be able to continue but may hit other issues we could see.

**Comment by ngfgrant** [comment]
I can't see an open issue relating to this, so commenting here. 

I am consistently experiencing this issue in strapi version `v4.23.1` Community Edition and node version `v18.20.2`. 

I am attempting to transfer `--from` our production instance to a local instance 

The error I receive locally is 

```shell
Starting transfer...
[2024-05-13 17:40:12.250] error: [FATAL] WebSocket is not open: readyState 3 (CLOSED)
Transfer process failed.

```

The logs on the remote production instance are:

```shell
[content] [2024-05-13 16:37:51] [2024-05-13 16:37:51.708] info: [Data transfer] Disabling http timeouts
[content] [2024-05-13 16:37:51] [2024-05-13 16:37:51.710] http: GET /admin/transfer/runner/pull (38 ms) 200
[content] [2024-05-13 16:39:31] [2024-05-13 16:39:31.665] info: [Data transfer] Restoring http timeouts
```

The transfer token has Full Access.

**Comment by Boegie19** [comment]
@ngfgrant Mind opening a new issue for this?

**Comment by ngfgrant** [comment]
@Boegie19 I have opened issue #20304 - thanks!

**Comment by sanjeev-pandey23** [comment]
The input by @alexbudin saved the day finally. Just transfer content using `--only content` and upload media separately. Thank you!

**Comment by Smoke3785** [comment]
@sanjeev-pandey23 How did you separately upload your content?

**Comment by eltitano** [comment]
my solution was not to use strapi

**Comment by PeterBowater** [comment]
V5 works fine now.

**Comment by senanyaa** [comment]
Hello, im facing the same problem on 5.23. 
`transfer --from --excludes files` works but if i includes files i get the websocket closed error.

**Comment by kaichii** [comment]
How to solve it? I still encounter this error, I use version 5.8.0.

<img width="1508" height="86" alt="Image" src="https://github.com/user-attachments/assets/5580a9d8-ade2-4f65-aa41-23154bc78cf7" />
