### ISSUE TITLE
Replace media function is not currently working since it is not uploading the new file I attempt to replace.

### ISSUE THREAD

**Issue by jfigueroapcs** [strapi/strapi#18250]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.5.1
- Strapi version: v4.13.7
- Database: PostgreSQL 12
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript: Javascript 

### The bug

Replace media function is not currently working since it is not uploading the new file I attempt to replace.

### Steps to reproduce the behavior

1. Go to Media Library
2.  Go to an image
3. Click Replace Media at the bottom
4. Select the new file
5. Click finish

### Additional context

The bug doesn't generate any kind of error alert or failure on the run console.

**Comment by tuphuc** [comment]
also not working on 4.14.2

**Comment by Boegie19** [comment]
You could work around this issue by reuploading and redirecting all relations that directed to the old image to the new one.

**Comment by jfigueroapcs** [comment]
Hi @Boegie19 

Could it be possible for you to explain more details about how to work around the issue? I was not quite able to understand what you meant, so a bit more of context will be highly appreciated.

**Comment by Boegie19** [comment]
> Hi @Boegie19
> 
> Could it be possible for you to explain more details about how to work around the issue? I was not quite able to understand what you meant, so a bit more of context will be highly appreciated.

Is not worth the trobel explainining in the next release it should be fixed.

**Comment by maruthasalamr** [comment]
Facing same issue in strapi v5.5.1 
any fix for v5?

**Comment by mukesh-thakur-dy** [comment]
Any update on this issue. I am facing same issue in Strapi V4.25.21

**Comment by kimkwanka** [comment]
Also having the same issue here, we're on Strapi v4.25.8

**Comment by nmalyarsky** [comment]
Still not working in v4.26.1.

UPD: it actually works, but does not update any preview images ever. See https://github.com/strapi/strapi/issues/10453.

**Comment by TheZodo** [comment]
> Still not working in v4.26.1.
> 
> UPD: it actually works, but does not update any preview images ever. See [#10453](https://github.com/strapi/strapi/issues/10453).

I saw your comment today in standup while discussing the issue with our team LOL @nmalyarsky
