### ISSUE TITLE
Strapi admin cannot select correct date using the date picker, date jumps to previous day

### ISSUE THREAD

**Issue by stxbrx** [strapi/strapi#18432]
### Required System information

- Node.js version: 14.21.1
- NPM version: 6.14.17
- Strapi version: 4.11.3
- Database: PostgreSQL 14.5 
- Operating system: Ubuntu 20.04.6 LTS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

- a client admin user based in Dallas, TX reported this issue to me 
- in Strapi Content Manager / Collection Type / Schedule  he tried to add another entry to existing schedule entries 
- when typing in 8/11/2023 the date automatically switched to 08/11/2023
- when selecting 08/11/2023 via date picker the date switched to 09/11/2023
- when selecting 07/11/2023 via date picker the date switched to 08/11/2023

### Steps to reproduce the behavior

I can reproduce the issue when changing my local time to Dallas, CST 
I cannot reproduce the issue when my time is set to BST or CST 

1. Go to Content Manager / Collection Type / Schedule 
2. Click on 'add an entry'
3. Type in 8/11/2023 in date field 
4. See date set to 07/11/2023
5. Select 08/11/2023 via date picker
6. See date set to 09/11/2023 

### Expected behavior

when typing in 8/11/2023 I expect the date to be set to 08/11/2023
when selecting 08/11/2023 via date picker I expect the date to be set to 08/11/2023

### Screenshots

<img width="1437" alt="Screenshot 2023-10-13 at 04 18 37" src="https://github.com/strapi/strapi/assets/147735558/6c7d65bb-653e-4197-bf13-deb87709b10f">
<img width="1437" alt="Screenshot 2023-10-13 at 04 18 33" src="https://github.com/strapi/strapi/assets/147735558/74c5c6e5-1783-4796-8f0b-6dd11177492a">
<img width="1437" alt="Screenshot 2023-10-13 at 04 18 08" src="https://github.com/strapi/strapi/assets/147735558/1aeb900b-1ec0-4df4-9802-d2853cd5e35a">
<img width="1437" alt="Screenshot 2023-10-13 at 04 17 47" src="https://github.com/strapi/strapi/assets/147735558/d4eaf5f1-f76a-47c5-bf27-d29f62a43204">
<img width="1437" alt="Screenshot 2023-10-13 at 04 17 34" src="https://github.com/strapi/strapi/assets/147735558/6ce0798b-ab58-4324-9335-bfae2b7e50bb">
<img width="1437" alt="Screenshot 2023-10-13 at 04 17 24" src="https://github.com/strapi/strapi/assets/147735558/69a1649c-0c18-4a7b-ace0-c028e1e9c11e">
<img width="1437" alt="Screenshot 2023-10-13 at 04 17 17" src="https://github.com/strapi/strapi/assets/147735558/b4eeb612-2b1a-4490-977f-99e209132501">

### Additional context

screen recording below
https://www.webcargo.net/l/sEaBe7fANZ/

**Comment by joshuaellis** [comment]
Have you tried updating your vesion of strapi? I'm very sure this was solved in a later version :)

**Comment by stxbrx** [comment]
@joshuaellis thanks, could not find any fixed issues in regards to date picker in release notes but will update and check

**Comment by muammerkeles** [comment]
Hi,
I am excited to say that I am currently developing date-range-picker plugin for strapi.
It allows you to use 1 field instead of two seperate date input field.

![image](https://github.com/strapi/strapi/assets/6603435/9fcaf3a7-7c47-48c8-8d72-c6ddec9362f9)

You may follow this;
https://www.npmjs.com/package/strapi-date-range-picker-plugin

**Comment by LucaNerlich** [comment]
This is a bug in the Design System Storybook.
DatePicker has two different props: selectedDate and value. Value is the correct one.
I ran into the exact same issue yesterday:

![image](https://github.com/strapi/strapi/assets/5942270/0f562b4e-8c39-4044-8e68-0cbeac4a3309)

**Comment by LucaNerlich** [comment]
Nevermind, still happens today with strapi 4.17 and design systen 4.14.1
![date](https://github.com/strapi/strapi/assets/5942270/23468f7c-0d57-43bc-8fe6-1b9e09c9ec5f)
```jsx


 <DatePicker onChange={setDate}
                                value={date}
                                ref={datePickerRef}
                                required
                                label="Datum"
                                initialDate={new Date()}
                                onClear={() => setDate(undefined)}
                    />
```

**Comment by stxbrx** [comment]
cheers @LucaNerlich, maybe next release then

**Comment by LucaNerlich** [comment]
@stxbrx found a fix by looking into the main strapi repo and their usage:

```
import formatISO from 'date-fns/formatISO';
 onChange={(date) => {
                            setDate(date ? formatISO(date, {representation: 'date'}) : null)
                        }}
```
you need the formatISO call in your datePicker onChange ...

**Comment by leosantacruz** [comment]
@LucaNerlich I don't see the Datepicker component at all in my Strapi v5.1.1 project. I'm facing the same problem. Thanks!
