### ISSUE TITLE
Localized content can't be published and displays "Warning: already.published"

### ISSUE THREAD

**Issue by alex-lechner** [strapi/strapi#19289]
### Required System information

- Node.js version: 20.11.0
- NPM version: 10.2.4
- Strapi version: 4.17.1
- Database: PostgreSQL
- Operating system: macOS 14.2.1
- Is your project Javascript or Typescript: Javascript

### Steps to reproduce the behavior

1. Go to `Settings > Internationalization` and click on `Add new locale`
2. Go to `Content-Typp Builder Manager > SINGLE TYPES`, select a single type of your choice, click on `Edit`, go to `Advanced Settings`, check the `Internationalization` checkbox and click on `Finish`
3. Go to `Content Manager > SINGLE TYPES`, click the single type from the previous step, choose the created localization (from Step 1) under `Locales` on the very right sidebar, fill out the fields, click on `Save` and then on `Publish`
4. An error message appears with `Warning: already.published`. However, the status shows `Editing draft version` for that locale (but not for the default locale). 

### Expected behavior

Published localized content that can be fetched from the API.

### Screenshots

![Screenshot 2024-01-19 at 18 26 37](https://github.com/strapi/strapi/assets/26361781/f5a5a1b0-9666-43e7-a08b-1382a2192b08)

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

Reference to closed issue #17314

**Comment by lidachao111222** [comment]
Well, there is a method that can temporarily solve this problem, although it might sound weird. I noticed that your German language setting is not the default. You could try setting it as the default language, then publish again, and afterwards revert back to the original default language. Then, you'll see that this issue has been resolved.  lol

**Comment by alex-lechner** [comment]
@lidachao111222  OMG that worked 😂 Thank you!

**Comment by alex-lechner** [comment]
@joshuaellis Just installed the new version 4.19.1 but the issue still occurs, unfortunately. Am I missing something?

**Comment by julesrenaud** [comment]
@alex-lechner it hasn't been released yet. The milestone on the PR is set to 4.20.0.

**Comment by zackthe** [comment]
I'm having the same issue here, is there any solution ??
![Uploading warning.PNG…]()

**Comment by alexgreenpol** [comment]
Have the same problem. Could you please fix that?

**Comment by nicolatournay** [comment]
> Well, there is a method that can temporarily solve this problem, although it might sound weird. I noticed that your German language setting is not the default. You could try setting it as the default language, then publish again, and afterwards revert back to the original default language. Then, you'll see that this issue has been resolved. lol

Thank you! This little trick worked for me as well.

**Comment by cgampe** [comment]
I'm on 4.20.1, the issue is still not resolved. Any plans on this?

**Comment by thewickest** [comment]
Hey,

I was playing around with it and the method that @lidachao111222 works but I found a faster way. I think the problem comes with the language selector inside the entity editor. What I did was: 

  - Create an entity in another language and Save it.
  - Go to the lists of entities outside the editor
  - Change the language there
  - Get inside a different language entity (which should be in Draft state)
  - Publish the entity again

It works for me. I hope it helps you. Looking forward this to solve.

**Comment by pascualmanuel** [comment]
Hey! 
I solved it by deactivating the option:
"**Draft & publish** - _Allows writing a draft version of an entry, before it is published_" from the single type or collection type settings. 
<img width="952" alt="Screenshot 2024-02-21 at 13 35 44" src="https://github.com/strapi/strapi/assets/92048968/61acb9aa-138c-4241-9569-36dce9901b70">

I hope it helps you.

**Comment by beeb** [comment]
@joshuaellis maybe re-open?
