### ISSUE TITLE
REST API and Content Manager returning different IDs for entries

### ISSUE THREAD

**Issue by MunasheHodza** [strapi/strapi#21967]
### Required System information

- Node.js version: Node 20
- NPM version: npm/10.5.2
- Strapi version: 5.1.0
- Database: Strapi Cloud
- Operating system: darwin arm64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

The Content Manager in the admin panel shows id numbers in odd numbers and the rest-api shows them as even numbers for the same entries!

### Steps to reproduce the behavior

1. Go to content manager and also make a rest api call
2. See error

### Expected behavior

IDs should match

### Screenshots

<img width="1140" alt="Screenshot 2024-10-24 at 12 15 02" src="https://github.com/user-attachments/assets/9c740a00-f343-4b2b-9d27-f9c823192116">
<img width="977" alt="Screenshot 2024-10-24 at 12 13 12" src="https://github.com/user-attachments/assets/dfc90a49-8bb0-4c55-81c0-9b481d273580">

**Comment by DarshanBorse** [comment]
Please assign me 👍

**Comment by derrickmehaffy** [comment]
> Please assign me 👍

We don't assign issues, just open a PR

**Comment by kasyap1234** [comment]
I have verified thiss issue, getting two different sets of IDs : 
one via content manager UI and one via REST API . 
content manager UI and core strapi 
The key difference is : 
uid.ts focuses on generating and validating UIDs for user input fields
Strapi.ts uses UIDs as system-level identifiers for content structure

**Comment by kasyap1234** [comment]
so using a single service for both api and content-manager should solve this issue

**Comment by jordisanchezcarbonell** [comment]
Hi, i have the same error , how can fix it ?

**Comment by derrickmehaffy** [comment]
This isn't really "intended" but the integer based IDs are useless in this case and we really should be showing the document ID instead in the content-manager which our product team is already aware of and are planning on working on this.

cc @yanniskadiri / @lucasboilly 

This is an internal video from one of our product designers about the initial design of this: 

https://www.loom.com/share/a9b87246cff84f5cb906a3725bf75e7b?sid=111510e4-b64a-40e0-b13c-6de2587becb1

**Comment by TruoYang** [comment]
I know I'm late.. but could you tell me is the bug solved? I got the same problem but it seems doesn't follow any rule, just two number randomly but never equal

**Comment by eevan7a9** [comment]
it's July 25, 2025. I still encounter the same issue has anyone found a solution for this?

**Comment by TruoYang** [comment]
> it's July 25, 2025. I still encounter the same issue has anyone found a solution for this?

https://dev.to/truoyang/solved-rest-api-and-content-manager-returning-different-ids-for-entries-370k
You can try my solution, I know it's not the best solution but it may fix temporarily for continuing the next period

**Comment by flyingduck92** [comment]
I got the same issue, its only created content with odd ID, not serial ID (in order)

**Comment by TruoYang** [comment]
Still wonder how this bug still exists till nowadays. Did they drop Strapi?
