### ISSUE TITLE
Error Upgrading Strapi from v4 to v5 (could not find react-redux context value)

### ISSUE THREAD

**Issue by arifinyudhy** [strapi/strapi#22075]
### Required System information

- Node.js version: v20.15.1
- NPM version: 10.8.0
- Strapi version: 5.2.0
- Database: postgres
- Operating system: Windows
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Upgrading Strapi v4 to v5

### Steps to reproduce the behavior

1. Remove plugins that are not compatible with Strapi v5
2. Comment out lifecycles
3. Upgrade Strapi
4. Run Strapi
5. The server is running, but an error appears when accessed

### Expected behavior

Able to successfully open the admin dashboard.

### Screenshots

![image](https://github.com/user-attachments/assets/10c6df6b-2818-4b5d-b2d3-4806ef2401de)

### Additional context

```
Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
    at useReduxContext2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-XNSXFZMB.js?v=9c9169f5:38363:13)
    at useStore2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-XNSXFZMB.js?v=9c9169f5:38500:9)
    at useDispatch2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-XNSXFZMB.js?v=9c9169f5:38513:19)
    at useQuerySubscription (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-XNSXFZMB.js?v=9c9169f5:38666:22)
    at useQuery (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-XNSXFZMB.js?v=9c9169f5:38845:40)
    at AuthProvider (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-YFRE323K.js?v=9c9169f5:4812:52)
    at renderWithHooks (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-52JPMTF2.js?v=9c9169f5:11568:26)
    at mountIndeterminateComponent (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-52JPMTF2.js?v=9c9169f5:14946:21)
    at beginWork (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-52JPMTF2.js?v=9c9169f5:15934:22)
    at beginWork$1 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-52JPMTF2.js?v=9c9169f5:19781:22)
```

**Comment by balalamba** [comment]
facing the same issue

**Comment by balalamba** [comment]
try v.5.1.1, it works for me

**Comment by arifinyudhy** [comment]
thanks for the suggestion let me try

**Comment by arifinyudhy** [comment]
> try v.5.1.1, it works for me
encounter the same error 
![image](https://github.com/user-attachments/assets/dcbd661b-6474-4917-b225-b0a3bd85aefa)
![image](https://github.com/user-attachments/assets/05d0fbdc-df26-454d-9049-5dfdd3d007ca)

**Comment by balalamba** [comment]
did you try `npm ci ` or to reinstall all dependencies ?

**Comment by arifinyudhy** [comment]
yes I did, but still encounter the same issue, I also try to remove my collection but still not working

**Comment by arifinyudhy** [comment]
solved in strapi v 5.3.0

**Comment by fchristl** [comment]
I encounter the same issue with 5.3.0 unfortunately.

**Comment by arifinyudhy** [comment]
try to add `react-redux": "9.1.2` on your dependencies

**Comment by fchristl** [comment]
> try to add `react-redux": "9.1.2` on your dependencies

Thank you, I appreciate the response. That does not solve it unfortunately.

**Comment by arifinyudhy** [comment]
> > try to add `react-redux": "9.1.2` on your dependencies
> 
> Thank you, I appreciate the response. That does not solve it unfortunately.

You're welcome, maybe you can try this
1. upgrade to version 5.1.1
2. then run  `npx @strapi/upgrade minor`
I hope it works for you.

**Comment by b-huessner** [comment]
I am having the same issue as @fchristl 
I tried everything described in here, but I can't get it to work.

**Comment by fchristl** [comment]
Does it make sense to re-open the issue, of shall we create a new one?

**Comment by Bubbafrost95** [comment]
I just had this issue when doing a major upgrade from v4 to v5.8.0. What ended up solving it for me was doing an `npm update`, and then it let me through to the admin dashboard.

**Comment by b-huessner** [comment]
Mh interesting.
Will give this a try once I get back to that ticket ;⁠-⁠)

**Comment by b0tm1nd** [comment]
For me `npm update` did not helped.
What really helped is:
```
#  rm -rf node_modules/ package-lock.json
#  npm i
```

**Comment by carrascojm** [comment]
> For me `npm update` did not help. What really helped is:
> 
> ```
> #  rm -rf node_modules/ package-lock.json
> #  npm i
> ```

I was having the same problem and this worked for me! Thanks

**Comment by r0emek** [comment]
In my situation, the error was caused by multiple instances of `react-redux` in the `node_modules `folder (leftover migration clutter).
Consolidating the dependency to a single version and running `npm i` fixed the problem.
