### ISSUE TITLE
Issue with Component Order Mismatch in Dynamic Zone After upgrade to v5.4.0

### ISSUE THREAD

**Issue by panupong-chaetan** [strapi/strapi#22250]
### Required System information

- Node.js version: 18.18.2
- NPM version: 10.9.0
- Strapi version: 5.4.1
- Database: mysql
- Operating system: windows 10
- Is your project Javascript or Typescript: Typescript

### Description of the Issue

The order of components displayed in the dynamic zone on localhost does not match the order configured in the Strapi admin panel. This discrepancy makes it difficult to ensure consistent rendering between the admin interface and the local environment.
This problem occured after upgrade from v5.3.0 to v5.4.0. 
Previously I used v5.3.0 without any problems.

### Steps to reproduce the behavior
1. Log in to the Strapi admin panel.  
2. Navigate to a content type that includes a **dynamic zone**.  
3. Add multiple components to the dynamic zone and arrange them in a specific order.  
4. Save the changes.  
5. Query the content type through the API or render it in the frontend on localhost.  
6. Observe that the order of the components displayed does not match the order configured in the admin panel.  

### Expected behavior

The order of components displayed on localhost should match the order set in the Strapi admin panel for the dynamic zone.

### Actual behavior

The order of components displayed on localhost is incorrect and does not align with the order set in the Strapi admin panel.

### Screenshots

![Screenshot 2024-11-24 145648](https://github.com/user-attachments/assets/0a8b84c9-904c-4a37-80ee-028900cac7cd)

![Screenshot 2024-11-24 145652](https://github.com/user-attachments/assets/6b85cafc-d445-4707-9f76-761161dbdb30)

![Screenshot 2024-11-23 152736](https://github.com/user-attachments/assets/9af09e90-bcf6-4091-8732-2956d5e38ded)

![Screenshot 2024-11-23 152344](https://github.com/user-attachments/assets/28d59fff-04ca-4bf8-aa92-df26611552b8)

![image](https://github.com/user-attachments/assets/0e368951-477f-44c4-a79b-006f5ec7bd38)

### Code snippets

![image](https://github.com/user-attachments/assets/04910c48-a637-44ae-9de0-dbb3e8bb12ce)

**Comment by simon-roland** [comment]
Pretty sure this is related to the issue described in #22228

**Comment by panupong-chaetan** [comment]
> Pretty sure this is related to the issue described in #22228

Yes, before upgrading from 5.3.0 to 5.4.0 it worked fine.

**Comment by DSK-QwQ** [comment]
Can confirm downgrading again fixes the issue. 5.4.0 is the culprit.

**Comment by derrickmehaffy** [comment]
This issue is in relation to 3 issues total impacting components, relations, and dynamic zones:

- Components: https://github.com/strapi/strapi/issues/22250
- Relations: https://github.com/strapi/strapi/issues/22228
- Dynamic Zones: https://github.com/strapi/strapi/issues/22170

**Comment by hanpaine** [comment]
Thanks for your additional comments and patience folks, we're taking a look now 🙏

**Comment by derrickmehaffy** [comment]
We have an experimental version for users to test with: `0.0.0-experimental.7bc5339b0393e53f9f568301594621e7fb466e2f`

Please don't use this in production, if you aren't sure how to use the experimental you just change all of the `@strapi/*` packages in your package.json to use this (except the SEO plugin), reinstall node_modules, and re-run the application.

If all goes well, we plan to merge this into tomorrow's release.

**Comment by hanpaine** [comment]
Fixed in 5.5.1, released today

**Comment by Convly** [comment]
> > Fixed in 5.5.1, released today
> 
> Thank you, but after the upgrade, I lost all data in the dynamic zone.

Hey @panupong-chaetan, could you open an issue with the exact steps you've done + the content structure you have in your app? (If the content models are too sensitive, you can send them by DM or mail).

Is the data still present in your database? Or did the `_cmps` table's content got deleted as well?
