### ISSUE TITLE
Relations Not Appearing in Content Manager for Main Content

### ISSUE THREAD

**Issue by santoshideal** [strapi/strapi#22576]
Node.js version: v20.10.0
    NPM version: 0.39.1
    Strapi version: 5.6.0
    Database: MYSQL
    Operating system: LINUX
    Is your project Javascript or Typescript: Javascript
    
**Describe the bug** :  I am experiencing an issue where related content no longer appears in the main content relation view of the Content Manager. As shown in the attached screenshot, while I can add a relation to the content, it does not display the related data within the main entry.

This issue happens when I create or edit an entry with relations. The relation seems to be saved correctly (it shows "Published"), but it does not reflect in the content view.
    

 
    Go to     Content Manager 
    Click on  Create new entity
    Scroll down to 'To add the content media (Relation Field)'
    See error (The Relational Content Media Selected Data is not appears in the content manager Content Table.
    
 Please check the Video 
[Content _ Strapi.webm](https://github.com/user-attachments/assets/475dfd78-a227-4802-ae6e-6a7e985e4475)

Also snap shot
![image](https://github.com/user-attachments/assets/bc5bff8e-f019-414e-89fb-89f6cfe10d36)
![image](https://github.com/user-attachments/assets/e217be20-deb7-4ba1-a6f2-a939350d0f0b)

    Thanks.

**Comment by simotae14** [comment]
Hello @santoshideal thanks for your description.
Unfortunately, your description doesn't follow the format we suggested in the Description of the Github Issue, this one



## Bug report

### Required System information






- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:



### Describe the bug

A clear and concise description of what the bug is.

### Steps to reproduce the behavior

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Expected behavior

A clear and concise description of what you expected to happen.

### Screenshots

If applicable, add screenshots to help explain your problem.



Can I ask you, if it is possible to provide us with these information because at the moment your issue is not totally clear 🙏🏽 
Also a video can be really useful

Thanks

**Comment by santoshideal** [comment]
Node.js version: v20.10.0
    NPM version: 0.39.1
    Strapi version: 5.6.0
    Database: MYSQL
    Operating system: LINUX
    Is your project Javascript or Typescript: Javascript
    
**Describe the bug** :  I am experiencing an issue where related content no longer appears in the main content relation view of the Content Manager. As shown in the attached screenshot, while I can add a relation to the content, it does not display the related data within the main entry.

This issue happens when I create or edit an entry with relations. The relation seems to be saved correctly (it shows "Published"), but it does not reflect in the content view.
    

 
    Go to     Content Manager 
    Click on  Create new entity
    Scroll down to 'To add the content media (Relation Field)'
    See error (The Relational Content Media Selected Data is not appears in the content manager Content Table
    
    Please check the Video link-

    [](https://www.awesomescreenshot.com/video/35320085?key=d7e2dec439280de540b1f24ccf980cae)
    
    Thanks.

**Comment by santoshideal** [comment]
[](https://www.awesomescreenshot.com/video/35320085?key=d7e2dec439280de540b1f24ccf980cae)

**Comment by simotae14** [comment]
ok thanks a lot for the update, can you please move the update here https://github.com/strapi/strapi/issues/22576#issue-2772038877

**Comment by santoshideal** [comment]
**Is there any update regarding the related issue?**

**Comment by TupiC** [comment]
Having the same issue with (Strapi 5.7.0). Removing the Draft & Publish option for my relational collection fixed the issue for me. I was still able to publish my draft again although I already published the document.

**Comment by derrickmehaffy** [comment]
This was fixed in 5.7.0+

**Comment by santoshideal** [comment]
Hello @simotae14 #22576

I’m currently facing an issue where the content related to a specific field no longer appears in the main content relation view of the Content Manager. Despite reviewing similar issues and potential fixes, the problem persists.

**Comment by simotae14** [comment]
@santoshideal please take a look at the last Strapi release, 5.8.0, the bug would be fixed

**Comment by santoshideal** [comment]
Hi @simotae14 ,

I have installed the latest version of Strapi, but unfortunately, the issue still persists. I’ve shared a snapshot in my previous comment for your reference. Please let me know if there’s any additional information or steps you’d like me to provide to help debug this further.

Looking forward to your guidance.

Thank you!

**Comment by simotae14** [comment]
Thank you @santoshideal then please open a new Github Issue trying to follow the template provided in the description textarea. Thanks again

**Comment by santoshideal** [comment]
Hi @simotae14,

I’ve created a new bug report. Please take a look when you get a chance.

For you reference :- https://github.com/strapi/strapi/issues/22675 

Thank you!
