### ISSUE TITLE
Select is missing a scrollbar inside modal

### ISSUE THREAD

**Issue by kristerlooga-bolt** [strapi/strapi#23205]
### Node Version

20.10.0

### NPM/Yarn/PNPM Version

9.12.2

### Strapi Version

5.10.2

### Operating System

Linux (Other)

### Database

SQLite

### Javascript or Typescript

Typescript

### Bug Description

When users click on "Fill in from another locale" button, the select is missing a scrollbar. Users are able to navigate the select with keyboard navigation. Ideally scroll should work.

I also tested with latest version of strapi 5.11.3 and the issue still persists. Also tested on a fresh strapi install.

### Steps to Reproduce

1. Have localisation enabled for content type
2. Have an entry with multiple localised versions
3. Click on "Fill in from another locale" button
4. Click on select
5. Attempt to scroll

### Expected Behavior

Scroll should work

### Logs

```shell

```

### Media

<img width="1126" alt="Image" src="https://github.com/user-attachments/assets/517ee822-9ce5-4462-be34-10adba627383" />

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by CodingLady22** [comment]
Hi, I’d love to work on this issue. Can I take it?

**Comment by hanpaine** [comment]
Hey @CodingLady22 absolutely! That would be very much appreciated 🙏

**Comment by PapatMayuri** [comment]
Hi @kristerlooga-bolt & @hanpaine , checked this issue in Internationalization on click of Add New Locale we got popup in which we have Locals dropdown we have scrollbar adding screenshot here,

<img width="448" alt="Image" src="https://github.com/user-attachments/assets/5fb7ec14-8e0c-4d46-a3cd-c3263cfb5900" />


In Relation also we have scroller working,
<img width="434" alt="Image" src="https://github.com/user-attachments/assets/7eab34cf-700a-472d-a701-19a6fe7d9de8" />

**Comment by williamwgant** [comment]
Also noted this morning that the mouse wheel doesn't seem to do anything either. That may be something to watch out for as well.

**Comment by ricosandyca** [comment]
@williamwgant I'm experiencing the same issue. I can't scroll using mouse wheel on any select inside a modal. But it works just fine if it's outside modal

**Comment by Adzouz** [comment]
Hi there! Thanks a lot for reporting the issue. We had a regression on the design-system and I just merged a PR that will fix it.
It will be released with the new version of the design-system. I'll keep you in touch on which version of strapi it will be released.
🚀

**Comment by CodingLady22** [comment]
@Adzouz thank you for the update on resolving the issue. Just to clarify, should I go ahead and look for another open issue to work on since this has already been fixed on the design system side? I'd love to get involved and contribute

**Comment by Adzouz** [comment]
Hi @CodingLady22 that's really appreciated! If you really want to contribute then yes, feel free to pick any other issue 😊 This one was really impacting the experience and one of our dev already had the solution so it was quite a quick win.
Have a great day 🚀

**Comment by Adzouz** [comment]
Hi,
The design-system was bumped in version 5.15.1 of Strapi that will be available later today.
Closing the issue 🚀

**Comment by kristerlooga-bolt** [comment]
Hi @Adzouz Thanks for the update!

I updated @strapi/strapi to 5.15.1 and @strapi/design-system to 2.0.0-rc.25, but the issue still persists. 

I see there has been an update from when I initially reported the issue, that there is a scrollbar now visible, but when trying to scroll using the mousewheel or trackpad nothing happens. Interestingly scroll with mousewheel does work, but only when the cursor is hovering on the scrollbar, but not when it is hovering on the dropdown content.

Additional information: Tested on a macbook on latest Safari and Chrome

**Comment by Adzouz** [comment]
Hi @kristerlooga-bolt,
I hope you're doing good! I was able to reproduce the issue and it's because it was fixed for modals but not for dialogs, I'm really sorry about that...
I'll make the fix asap so it would be available on next release 🤞
Sorry again and thank you for your patience 🙏
