### ISSUE TITLE
Strapi V5 not remove collection in production

### ISSUE THREAD

**Issue by red-made** [strapi/strapi#23805]
### Node Version

20.0.0

### NPM/Yarn/PNPM Version

10

### Strapi Version

v5.8.0

### Operating System

Linux (Debian/Ubuntu)

### Database

MariaDB

### Javascript or Typescript

Typescript

### Bug Description

I have worked with Strapi v4 and currently have an active project using it. When I delete a content type and then push the changes to the server and rebuild the project, the content type is removed, including all its related data in the database.

With Strapi v5, I did the same thing: I needed to remove some content types, so I deleted them locally and then pushed the changes to the server. However, the content types are still there.

### Steps to Reproduce

Steps to Reproduce
- Create a Strapi v5 project locally.
- Generate a content-type (e.g., article).
- Push the project to a server and run a build.
- Confirm the content-type appears in the admin panel.
- Delete the content-type locally (e.g., remove src/api/article).
- Push the changes to the server.
- Run build and restart Strapi on the server.

### Expected Behavior

The deleted content-type should no longer appear in the admin panel.

### Logs

```shell

```

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

**Comment by OcneanuVlad** [comment]
Hi, thanks for reporting the issue!

In Strapi v5, deleting a content type involves more than just removing the src/api/<content-type> folder. This action alone does not remove associated database tables, metadata, or other internal references, which can lead to unexpected behavior. To properly delete a content type, always use the admin panel, as it ensures all related data and configurations are correctly cleaned up.

**Comment by red-made** [comment]
Thanks for your reply!

In production, where the Content-Type Builder is disabled, how can I safely remove a content type and clean up the database and all related configurations?

**Comment by OcneanuVlad** [comment]
You're welcome!

That said — you should never remove a content type directly in production. This is not a safe or recommended practice.

If you really must, it is technically possible (as it was in Strapi v4) to manually delete the content type folder (usually under src/api/your-content-type) and then rebuild the project. If everything is properly removed and cleaned, it should compile and build without issues. Strapi watches all files, and once it detects a change, it rebuilds itself. If it doesn't, it's likely due to your deployment or build process not handling the cleanup correctly.

However, we strongly discourage this approach. The correct and safe way to manage content types — including removing them — is to:
1. Do all content type modifications (creation, updates, deletions) in your development environment using the Content-Type Builder.
2. Make sure the app builds and behaves as expected locally.
3. Commit those changes to your codebase (including schema updates and any related files).
4. Push the changes to your production environment via your normal deployment pipeline.

This ensures your production environment stays stable and avoids database inconsistencies or app crashes.

**Comment by red-made** [comment]
I completely agree with everything you said — and this is exactly the flow I follow.

However, in production and development, the data often differs. For instance, I recently needed to clean up some unused content types to keep the admin panel cleaner and more manageable.

So in development, I remove the content types using the Content-Type Builder. In production, I manually delete all related data, so that those collections are empty.

Then I push the updated code — and what happens is that in production, the content types are still visible in the admin panel and technically still active (you can still add entries), even though the code no longer defines them.

In Strapi v4, when I pushed code after deleting a collection, it would disappear from the admin UI — which, while risky, at least removed it entirely.

In Strapi v5, though, the collections remain in the schema. That means I would have to:

- Import the production DB into development
- Remove the content types there
- Push the code
- And deploy the updated DB

This round-trip is quite complex and time-consuming.

Is there really no simpler alternative? Ideally, I’d like Strapi to update the DB schema and remove the unused content types — just like it did in v4 — without relying on migrations.

**Comment by OcneanuVlad** [comment]
What you’re describing sounds like an issue with the build process not working as expected.

During build time, Strapi scans your project files and updates the database schema and admin panel to match the current code. If deleted content types are still showing up, it likely means the build isn't running cleanly.

Make sure your production environment is actually rebuilding the app correctly, and that no caching system (like Docker, CI cache, or .cache/build folders) is causing it to use old data.

**Comment by red-made** [comment]
You pointed me in the right direction. I noticed that the old content-types were still inside the dist folder, so I manually deleted dist and rebuilt the project.
