### ISSUE TITLE
Deleting field with files breaks /upload/files

### ISSUE THREAD

**Issue by davidchalifoux** [strapi/strapi#2933]
**Informations**
- **Node.js version**: v10.15.2
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: Postgres
- **Operating system**: Ubuntu 18

**What is the current behavior?**
`/upload/files` returns an error:
`{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}`
From the log:

> TypeError: Invalid attempt to destructure non-iterable instance
>     at /root/library/node_modules/babel-runtime/helpers/slicedToArray.js:48:13
>     at Object.morphCandidate (/root/library/node_modules/bookshelf/lib/helpers.js:37:47)
>     at /root/library/node_modules/bookshelf/lib/eager.js:115:34
>     at /root/library/node_modules/lodash/lodash.js:13402:38
>     at /root/library/node_modules/lodash/lodash.js:4911:15
>     at baseForOwn (/root/library/node_modules/lodash/lodash.js:2996:24)
>     at Function.mapValues (/root/library/node_modules/lodash/lodash.js:13401:7)
>     at EagerRelation.morphToFetch (/root/library/node_modules/bookshelf/lib/eager.js:114:43)
>     at EagerRelation.eagerFetch (/root/library/node_modules/bookshelf/lib/eager.js:85:21)
>     at EagerRelation.<anonymous> (/root/library/node_modules/bookshelf/lib/base/eager.js:74:33)
> From previous event:
>     at /root/library/node_modules/bookshelf/lib/eager.js:152:75
> From previous event:
>     at EagerRelation._eagerLoadHelper (/root/library/node_modules/bookshelf/lib/eager.js:140:35)
>     at Sync.<anonymous> (/root/library/node_modules/bookshelf/lib/eager.js:89:23)
> From previous event:
>     at EagerRelation.eagerFetch (/root/library/node_modules/bookshelf/lib/eager.js:88:114)
>     at EagerRelation.<anonymous> (/root/library/node_modules/bookshelf/lib/base/eager.js:74:33)
> From previous event:
>     at Child._handleEager (/root/library/node_modules/bookshelf/lib/collection.js:459:73)
>     at Child.<anonymous> (/root/library/node_modules/bookshelf/lib/collection.js:154:21)
>     at runCallback (timers.js:705:18)
>     at tryOnImmediate (timers.js:676:5)
>     at processImmediate (timers.js:658:5)
>     at process.topLevelDomainCallback (domain.js:120:23)
> From previous event:
>     at Child.<anonymous> (/root/library/node_modules/bookshelf/lib/collection.js:152:6)
> From previous event:
>     at Child.fetchAll (/root/library/node_modules/bookshelf/lib/model.js:872:8)
>     at Function.find (/root/library/plugins/upload/config/queries/bookshelf.js:29:8)
>     at Object.fetchAll (/root/library/plugins/upload/services/Upload.js:137:8)
>     at find (/root/library/plugins/upload/controllers/Upload.js:120:65)
>     at dispatch (/usr/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
>     at next (/usr/lib/node_modules/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
>     at dispatch (/usr/lib/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
>     at policies.push (/usr/lib/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:59:26)
>     at dispatch (/usr/lib/node_modules/strapi/node_modules/koa-compose/index.js:42:32)
>     at module.exports (/root/library/plugins/users-permissions/config/policies/permissions.js:68:9)

**Steps to reproduce the problem**

- Create content type with file field

- Create entry of content type with an uploaded file

- Delete file field on content type

**What is the expected behavior?**

- Should not break `upload/files` when removing a file field.

**Suggested solutions**

- Remove files after removing file field?

- Leave files in non-relational purgatory after removing file field?

**Comment by davidchalifoux** [comment]
Update: I added a different file field to the content type and the error has disappeared.

**Comment by lauriejim** [comment]
Hello @davidchalifoux !

Thank you for this bug report.
We are currently on higher topic on our side. We will appreciate if you are able to investigate and help us on this point.

Thank you for your time.

**Comment by lauriejim** [comment]
This issue has been fixed in the beta (at least the beta.15 version)
I close this issue.

**Comment by webcoderkz** [comment]
FYI: when you delete a media field with contentes (image for example), you have to delete it manually from DB in `upload_file_morph` table, then error would disappear.

**Comment by JozefCulen** [comment]
Why is this, sill not solved.

**Comment by a1tem** [comment]
Hm, it's really strange, I have the same issue and this is not fixed yet

**Comment by a1tem** [comment]
> FYI: when you delete a media field with contentes (image for example), you have to delete it manually from DB in `upload_file_morph` table, then error would disappear.

I have both tables empty `upload_file_morph` and `upload_file` I use the latest version of strapi 3.2.5 and anyway I have this error.

<img width="1214" alt="Снимок экрана 2020-11-09 в 14 42 11" src="https://user-images.githubusercontent.com/1446261/98542589-d68f7a80-2299-11eb-9c3f-e0ef221e4724.png">

**Comment by derrickmehaffy** [comment]
see: https://github.com/strapi/strapi/issues/6347

A PR was merged 3 days ago that should be in the next release: https://github.com/strapi/strapi/pull/8548
