### ISSUE TITLE
what is "add new localization" exactly do ?

### ISSUE THREAD

**Issue by IDNatte** [strapi/strapi#3169]
**Informations**
- **Node.js 10.15.1**: 
- **NPM 6.9.0**: 
- **Strapi 3.0.0-alpha26**: 
- **Database sqlite**: 
- **Operating system Windows**: 
- **(Optional) Link to your Project**: 

when i wanna "add new localization" through configuration in strapi adminUI, i just only get this blank page like you would see in this image

did it bug ? did it not implemented yet ? sorry if i post the wrong format about bug report tho...

![b](https://user-images.githubusercontent.com/35636456/56498146-0a2d7700-6533-11e9-97cd-a7eb8a1573ed.png)

**Comment by lauriejim** [comment]
Hello! You said you are with `alpha.26` version, but this issue has been fixed in this version.
I think you update your app from a previous version of Strapi.
Make sure you also update your plugins version as said in the migration guides https://strapi.io/documentation/3.x.x/migration-guide/migration-guide-alpha.25-to-alpha.26.html

This feature create a new file in your `./config/locales` folder. Usefull for backend translation - see i18n feature.

**Comment by derrickmehaffy** [comment]
@lauriejim I tried hitting that button on a fresh project and got the same thing. Blank screen (locally and deployed)

**Comment by IDNatte** [comment]
@lauriejim @derrickmehaffy actually i've got this since alpha24 tho, so i wonder it under construction or something, and after i upgrde everything to alpha26 yesterday or before yesterday, it's still exists tho... this picture i take on my fresh upgraded alpha26. but yeah i've got nothing upgraded in plugin lvl, i'll try tomorrow.

**Comment by lauriejim** [comment]
Did you have errors in your browser console please.
And what is the browser you use ?

**Comment by IDNatte** [comment]
There is no console error both in from browser and terminal in dev mode

My browser is firefox quantum 66.0.3 64-bit

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

I con't really help you without more details to be able to reproduce.

**Comment by IDNatte** [comment]
oh well... maybe for the time being i'll close this issue to... :D
