### ISSUE TITLE
Strapi Start Admin Page: an error occurred during models config fetch

### ISSUE THREAD

**Issue by indper** [strapi/strapi#362]
**Node.js version**: 8.9.1
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha6.7
**Operating system**: Ubuntu 16.04.3 LTS
**MongoDB**: v3.4.10

Hi, 

I was install STRAPI & start the service but i found error : an error occurred during models config fetch. 
Please explain how to solve the problem..

Thank you.
Indra

**Comment by uniibu** [comment]
This most likely to happen if you use a different `http://hostname:1234` other than `http://localhost:1337` because the admin plugin still uses `http://localhost:1337` to make request to other plugins such as `http://localhost:1337/content-manager/models`, no matter what is on the config. Afaik, this has been fixed on alpha.7

**Comment by soupette** [comment]
I'll close the issue feel free to reopen it if you still encounter this problem

**Comment by ohsodhaara** [comment]
@lauriejim  i am facing the same problem no matter what i do 

the problem is that after i make a content type and then click on that type on the left hand side bar
strapi is unable to show any content ( even if there is no content ) 
the error strapi gives me is => **AN ERROR OCCURED DURING MODELS CONFIG FETCH**

Please help me out on this, i just can't figure this out !!

**Comment by ohsodhaara** [comment]
@lauriejim @soupette 
Please have a look at this error, !

**Comment by HenrijsS** [comment]
This issue is still present on 3.4.6

Also, it's not possible to connect to Mysql without giving the user mysql_native_password identifier.

**Comment by sanliverpool13** [comment]
The fact that this is still not resolved and ignored by Strapi ... Amazing

**Comment by SangramChavan** [comment]
This issue is still present on v3.6.8

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
