### ISSUE TITLE
yarn/npx create-strapi-app not working with MongoDB

### ISSUE THREAD

**Issue by joelbqz** [strapi/strapi#4751]
**Describe the bug**
yarn/npx create-app project-name is not working with MongoDB.

**Steps to reproduce the behavior**
Try to create a fresh install with Mongo

**Expected behavior**
⛔️ Connection test failed: Cannot find module '/var/folders/qw/j8cx72jn3j33qdd89yb01fcw0000gn/T/strapiba38398c3725/node_modules/mongoose/lib/utils/connectivity.js'

**Screenshots**
![image](https://user-images.githubusercontent.com/19965325/71093400-1aa3f900-2177-11ea-9f56-a169b38592a9.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v12.13.1
- NPM version: 6.12.1
- Database: Mongo
- Operating system: MacOS Mojave

**Comment by alexandrebodin** [comment]
Hi @joelbqz,  This issue has been fixed in beta.18.1 ;)

**Comment by joelbqz** [comment]
Hi @alexandrebodin thanks for your response, how it exactly solves the issue when I don't have strapi installed globally?

Best!

**Comment by alexandrebodin** [comment]
If you are running `yarn create strapi-app` or `npx create-strapi-app` it should work. Make sur you don't have `create-strapi-app` installed globally first

**Comment by tonxxd** [comment]
Hi I am still encountering the same issue.
I uninstalled the global create-strapi-app package as suggested and run

```yarn create strapi-app project```

![Schermata 2020-03-18 alle 10 34 20](https://user-images.githubusercontent.com/2827496/76946681-af4bfd80-6904-11ea-9bcd-d79d06a5c66e.jpg)

**Comment by alexandrebodin** [comment]
Hi @tonxxd this isn't the same issue. yours is sth wrong with yarn directly. What version are you using ?

**Comment by tonxxd** [comment]
You are right, sorry I didn't check the description correctly.
Could be a problem with yarn itself? 
yarn 1.21.1
node v13.6.0

**Comment by alexandrebodin** [comment]
I think the issue is with node v13. Can you try on node 12 plz ?

**Comment by tonxxd** [comment]
Yes I confirm, with node 12 works.
Thanks for finding the issue!

**Comment by wjchat** [comment]
Hi! I'm running strapi beta.20.3 and I'm getting that same error. Node v12, windows O/S. Any idea what the problem might be?

![image](https://user-images.githubusercontent.com/15861442/81579667-6c455e00-937a-11ea-8592-823ae558872c.png)

**Comment by alexandrebodin** [comment]
Hi @wjchat This happens when your system doesn't allow or fails silently to install packages in a tmp directory. What you Can do to avoid this is create the project with the cli options so it doesn't try to test the connection or with the quickstart and then change the database options in the config. I think we will add a --no-db-check to allow user to bypass this interactive check

**Comment by GeFeSTTS** [comment]
Hello, have strange issue on my Ubuntu when i try to npx create-strapi-app using Mongo (mongo is working).
![Screenshot from 2020-10-08 14-34-10](https://user-images.githubusercontent.com/43075229/95453449-8b6d0980-0973-11eb-8b7d-c43f48d54ed9.png)
