### ISSUE TITLE
Secure /uploads

### ISSUE THREAD

**Issue by wdhodges** [strapi/strapi#4956]
Sorry for yet another issue. I'm wondering if there is a way to secure `/uploads`? I've searched the documentation but can't figure it out. The public role does not have any permissions to the upload field, however I can still see a uploaded file without being authenticated. Is there a way to secure a particular upload or are they always public?

**Comment by derrickmehaffy** [comment]
@wdhodges sorry can you use the feature request template (you can just edit your OP) I know it can be a bit of a pain but like to try and keep the BR/FR/Discussion issues fairly clean. I'll reopen once you have tweaked it :)

> This is a templated message

Hello, please follow the feature request template.

A proper issue submission let's us better understand the purpose behind your feature request to better understand if it could be implemented.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. Please also submit your feature request on the [Product Board](https://portal.productboard.com/strapi/tabs/2-under-consideration)

Please update the issue, and reply back so it can be reopened.

Thank you.

> A copy of the feature request template can be found below:

```
<!--
Hello 👋 Thank you for submitting a feature request.

We are using ProductBoard to manage our roadmap and feature requests.

Can you please submit your feature request here: https://portal.productboard.com/strapi
-->

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
```

**Comment by lauriejim** [comment]
Hello!  You can here manage this route access.
Roles & Permissions > Role Name > Upload > `upload`
Screenshot bellow.
![Screen Shot 2020-01-14 at 5 54 57 PM](https://user-images.githubusercontent.com/5716596/72364593-10820580-36f7-11ea-9a40-27be3f1a57e7.png)

**Comment by wdhodges** [comment]
You sir are a saint, I guess I looked over that haha

**Comment by wdhodges** [comment]
@lauriejim I tried your method, however it's not working. When I upload a file, I get the URL and then open an incognito browser and navigate to it. I still shows. So I think that permission may be broken?

**Comment by lauriejim** [comment]
Ho, you want to restrict access to a file?

**Comment by wdhodges** [comment]
Got it. Thank you for letting me know!

**Comment by VMonsch** [comment]
Hey @lauriejim, can't seem to find the issue you're referencing. Can you provide a link ? Thanks!

**Comment by baermathias** [comment]
@VMonsch @lauriejim means maybe this one: https://github.com/strapi/strapi/issues/8623 ??
IMO this issue, should be fixed soon. Strapi is a content management system and in this case we have content open to the general public. If this is not on Strapis roadmap, then it should be mentioned in the documentation, So that developers can make a proper decision whether to use Strapi or another CMS. Because with this issue, you are not able to provide basic documents like invoices, orders and other user related documents.

**Comment by baermathias** [comment]
Duplicate of #8623

**Comment by mywebartist** [comment]
very true @baermathias im doing app for picture uploads but they need to be authenticated access. sucky

**Comment by mcnaveen** [comment]
Still not possible right? with the direct URL, non-authenticated users can access the file.

**Comment by derrickmehaffy** [comment]
> Still not possible right? with the direct URL, non-authenticated users can access the file. 

No it's not, the media library isn't designed for private files. It's not a DAM (Digital asset management system).
