### ISSUE TITLE
Forgot-password works but returns 500 Internal Server Error

### ISSUE THREAD

**Issue by lsliwaradioluz** [strapi/strapi#5249]
**Describe the bug**
While using forgot-password in Strapi, the email with link to reset password is sent but the axios.post request throws a 500 Internal Server Error. Strapi console logs an error "Argument passed in must be a single String of 12 bytes or a string of 24 hex characters"

**Steps to reproduce the behavior**
1. Create a new user in Strapi admin panel 
2. Go to Postman
3. Create post request to http://localhost:1337/auth/forgot-password
4. Use { email: user_email } as data 

**Expected behavior**
Strapi forgot-password sends and email without throwing an error at the same time 

**Screenshots**
![image](https://user-images.githubusercontent.com/39009379/74593744-d924b280-502e-11ea-9635-612a99054d13.png)

![image](https://user-images.githubusercontent.com/39009379/74593755-02454300-502f-11ea-8541-a3ad6b1fc143.png)

**System**
- Strapi version: 3.0.0-beta.18.4
- Database: mongoDB
- Operating system: Windows10

**Comment by derrickmehaffy** [comment]
Please test with the latest release

**Comment by lsliwaradioluz** [comment]
Updated, bug still occurs

```
"dependencies": {
    "axios": "^0.19.2",
    "strapi": "3.0.0-beta.18.7",
    "strapi-admin": "3.0.0-beta.18.7",
    "strapi-connector-mongoose": "3.0.0-beta.18.7",
    "strapi-plugin-content-manager": "3.0.0-beta.18.7",
    "strapi-plugin-content-type-builder": "3.0.0-beta.18.7",
    "strapi-plugin-email": "3.0.0-beta.18.7",
    "strapi-plugin-graphql": "3.0.0-beta.18.7",
    "strapi-plugin-upload": "3.0.0-beta.18.7",
    "strapi-plugin-users-permissions": "3.0.0-beta.18.7",
    "strapi-provider-email-sendgrid": "^3.0.0-beta.18.7",
    "strapi-provider-upload-cloudinary": "^3.0.0-beta.18.5",
    "strapi-utils": "3.0.0-beta.18.7"
  },
```

**Comment by derrickmehaffy** [comment]
Not that it's directly related @lsliwaradioluz `"strapi-provider-email-sendgrid": "^3.0.0-beta.18.7",`

For Strapi beta, you should make sure packages don't contain a carrot `^` before the version as it could grab the wrong one, this is until Strapi goes into stable and follows the standard version system. (NPM gets confused and just takes whatever the latest version is, even if it isn't in the beta tag)

Just a side point. :)

**Comment by lauriejim** [comment]
Hello! I just tried with the last version of Strapi (beta.18.7) and it works well.
Here is what I did - https://www.loom.com/share/2ba8316191fa43b48477b6c72a81ed25
At the end, I'm not showing the email, but I received it.

**Comment by lsliwaradioluz** [comment]
@lauriejim did you receive any error message ?

**Comment by baldeepsinghkwatra** [comment]
I am also facing the above issue 
<img width="961" alt="Screenshot 2020-03-02 at 8 53 52 PM" src="https://user-images.githubusercontent.com/14240722/75689898-fb256280-5cc7-11ea-8f4a-55e29bd5b1ef.png">

**Comment by tylercreller** [comment]
Seeing this error as well on beta.19, any progress here?

`  "dependencies": {
    ...
    "strapi": "3.0.0-beta.19",
    "strapi-admin": "3.0.0-beta.19",
    "strapi-connector-mongoose": "3.0.0-beta.19",
    "strapi-plugin-content-manager": "3.0.0-beta.19",
    "strapi-plugin-content-type-builder": "3.0.0-beta.19",
    "strapi-plugin-email": "3.0.0-beta.19",
    "strapi-plugin-graphql": "3.0.0-beta.19",
    "strapi-plugin-upload": "3.0.0-beta.19",
    "strapi-plugin-users-permissions": "3.0.0-beta.19",
    "strapi-provider-email-sendgrid": "3.0.0-beta.19",
    "strapi-utils": "3.0.0-beta.19"
  },`

**Comment by selbersuess** [comment]
same error with "strapi": "3.0.0-beta.19" for "/forgot-password" and "/reset-password". 
the problem seems to be updating the user by passing the hole user-object instead of only passsing the changing fields
i fixed with workarround using Auht.js as extension (to overwrite original methods) and changing following lines:

forgot-password (...controllers/Auth.js line 379):
 
await strapi
      .query('user', 'users-permissions')
      .update({ id: user.id }, user);

changed to

await strapi
      .query("user", "users-permissions")
      .update({ id: user.id }, { resetPasswordToken: resetPasswordToken });

***********************************************
changePassword (...controllers/Auth.js line 211):

await strapi
      .query('user', 'users-permissions')
      .update({ id: user.id }, user);

changed to

await strapi
        .query("user", "users-permissions")
        .update(
          { id: user.id },
          {
            resetPasswordToken: user.resetPasswordToken,
            password: user.password
          }
        );

**Comment by gabrielcramer** [comment]
Thanks @selbersuess. I had the same problem with "strapi": "3.0.0-beta.19" and those changes fixed the issue.

**Comment by super-kamil** [comment]
Still exists in 3.0.0-beta.20

**Comment by tunjioye** [comment]
The error still occurs in `3.0.0-beta.20`
I have narrowed it down and realised the error only occurs whenever I have a filled **has and belongs to one** relation to my users table / content type.

**Comment by tunjioye** [comment]
Until this issue is resolved, 
I have changed the relation to **User has many** and then I select and use the 1st object of the related content type.

**Comment by damtsnkff** [comment]
I could reproduce what @tunjioye said.

**Step to reproduce:**
- Fresh install of a Strapi project (with mongoDB config).
- Install the sengrid email provider (bc somehow with default sendmail provider doesn't work)
- Create a user `POST` `/auth/local/register` --> Ok
- Try forgot password `POST` `/auth/forgot-password` --> Ok
- Add a new collection for example `Bookings` with a field relation `has and belong to one` with the `users` collection.
- Try the forgot password `/auth/forgot-password` ---> `Error`

The error has the following message:

```
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/Users/damientsenkoff/Desktop/reset-pwd-issue/node_modules/bson/lib/bson/objectid.js:59:11)
    at Object.keys.reduce (/Users/damientsenkoff/Desktop/reset-pwd-issue/node_modules/strapi-connector-mongoose/lib/relations.js:135:28)
    at Array.reduce (<anonymous>)
    at Function.update [as updateRelations] (/Users/damientsenkoff/Desktop/reset-pwd-issue/node_modules/strapi-connector-mongoose/lib/relations.js:97:68)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Fix:**
@selbersuess is right, this seems to be a MongoDB issue only.
In `strapi-plugin-users-permissions > controllers > Auth.js`, inside the `forgotPassword` function, line 371.

replacing this line
https://github.com/strapi/strapi/blob/1ab5afc33da560f0944fbd2615ea62fb878bb07d/packages/strapi-plugin-users-permissions/controllers/Auth.js#L366

by fixes the issue.
```
await strapi.query('user', 'users-permissions').update({ id: user.id }, { resetPasswordToken });
```

Happy to send a PR if needed.

**Comment by lauriejim** [comment]
Thank you for these steps, I confirm this issue.
Can you please submit a PR to fix this issue.
I will appreciate your contribution.
Thank you.

**Comment by damtsnkff** [comment]
@lauriejim here you go: https://github.com/strapi/strapi/pull/6327

The issue happened in both the `changePassword` and `forgotPassword` methods so I went ahead and updated them both.

**Comment by lauriejim** [comment]
Thank you, I will have a look soon as possible.
