### ISSUE TITLE
Creating a new strapi app in a path with spaces fails

### ISSUE THREAD

**Issue by mikedevita** [strapi/strapi#631]
**Node.js version**:
9.5.0

**npm version**:
5.6.0

**Strapi version**:
3.0.0-alpha.9.3

**Operating system**:
MacOS Sierra (10.12.6)

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
broken, cannot use any paths with spaces in them

**If the current behavior is a bug, please provide the steps to reproduce the problem**

1. Create a directory such as `/tmp/Web/Example Client`: `mkdir -p "/tmp/Web/Example Client"`
2. run `cd /tmp/Web/Example Client`
3. try to create a new app via `strapi new api`
4. Error will present saying "no such file or directory", see screenshot for example
  a. ![image](https://user-images.githubusercontent.com/2991640/36111458-6aa992ae-0fe3-11e8-98d3-571fc65bd4f7.png)

**What is the expected behavior?**
Strapi should create the new app, taking into account the spaces in the directory path.

**Comment by denislutz** [comment]
With all the respect, empty spaces in folders are a sure path for bugs in all build frameworks across any stack. So why would you need to do this? I think we should not take the time of the community to deal with unimportant issues like this.

**Comment by lauriejim** [comment]
Hi @mikedevita. You just have to remove your space and it will work.
If you want you can try to fix it and submit a PR to help the community :)

**Comment by mikedevita** [comment]
Its fine, I have my web directory synced via One Drive which is symlinked to `~/One Drive - For Business/Web` OneDrive created this folder automatically, assuming its just a matter of escaping the path properly it should be a relatively simple fix but without digging into the code I can only guess. 

I'll dig into it more if it get time and submit a PR.

**Comment by JanPokorny** [comment]
Why is this closed, when the problem is still present? I agree that spaces in a folder name aren't usually a good idea, but this is surely a "bug" and not a "feature".

**Comment by JanPokorny** [comment]
@derrickmehaffy I have actually tried WSL first, but encountered several problems. Setting it up under Windows was my backup solution. I may revisit WSL later and see what was the problem, but now I'm too excited to actually try Strapi. 😁

**Comment by derrickmehaffy** [comment]
@JanPokorny It is fun, I've been around here a while. I would also highly suggest joining the slack too: https://slack.strapi.io

**Comment by mikedevita** [comment]
@JanPokorny one of the reasons why I dropped Strapi, was because of its limitations on the spaces in the directory. It's pretty much unavoidable on my work setup :\.

**Comment by JanPokorny** [comment]
@mikedevita That's sad. I understand why this is not seen as a large issue by the Strapi team -- it's usually work-aroundable by directory links or such. Except for the cases it isn't, of course. Also, having to do a workaround as a first thing isn't the best first impression 😁

**Comment by marcusungarette** [comment]
I'm facing the same problem,
resolved trying this aproach lets see whats happen after that 
-> https://codeburst.io/changing-a-profile-name-in-windows-9da6c02234e4

**Comment by Adit-COCO-Garg** [comment]
Use npx instead of Yarn:
`npx create-strapi-app my-project --quickstart`

**Comment by aviral** [comment]
The issue is not just restricted to the fact that the entire project path shouldn't have spaces but on windows if the windows username has spaces it leads to build issues as well as the temp files are being stored in the "C:/Users/User Name" folder. This is a lot more serious than people are letting on at the moment.

NPX quickstart script also does not run in this case.

**Comment by JanPokorny** [comment]
Thankfully new Windows installs use the first 5 letters of your email address as the account folder name, so no more spaces for everyone. Spaces can still occur in locally created accounts though. (Furthermore, changing the folder name for an existing account is _difficult difficult lemon difficult_. Trust me, I tried once and completely borked my install. It's literally easier to create a new local user and copy everything over.)

Kinda weird that this issue is closed and still not addressed? If anyone is still concerned about it, I'd suggest you create a new one since this one was closed with "haha just remove the space" without considering the broader context.

(Or just use Docker + VSCode Dev Container extension, it takes a bit to learn but it's literally an universal solution for all environment-related issues. It can even run GUI apps.)

**Comment by derrickmehaffy** [comment]
Considering how old this issue is, if someone could just open a new one with some more up to date debug information that would be great.

**Comment by newnormalstar** [comment]
I too was facing this issue in my local windows pc(since my name contains space). I almost stopped using strapi since than. I think Strapi team should take a consideration to fix it. There could be workaround...but its definitely a blocker for anyone who like to practice Strapi. Strapi cannot be only for the Pro btw.

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
